import {readFileSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {CombatSession,parseBattleEncounterSet} from '../src/engine/turn-based-combat';
import {createCharacterState,parseCharacterProfileSet,parseMartialArtSet} from '../src/engine/character-progression';
const read=(p:string)=>JSON.parse(readFileSync('data/base/'+p,'utf8'));
function setup(kind:'heal'|'attack'='heal',power=7,everyPlayerActions=2){const pp=parseCharacterProfileSet(read('characters/round-04-profiles.json')),ap=parseMartialArtSet(read('skills/round-04-martial-arts.json')),bp=parseBattleEncounterSet(read('battles/round-83-east-coast-encounters.json'));if(!pp.ok||!ap.ok||!bp.ok)throw Error('base');const profile=pp.set.profiles[0]!,player=createCharacterState(profile),encounter=structuredClone(bp.set.encounters[0]!);player.health.current-=30;return {player,encounter,profile,martialArts:new Map(ap.set.martialArts.map(a=>[a.id,a])),session:new CombatSession({encounter,profile,player,martialArts:new Map(ap.set.martialArts.map(a=>[a.id,a])),companion:{name:'同行测试人',support:{kind,power,everyPlayerActions}}})};}
describe('Round135 actual companion support receipts',()=>{
 it('second accepted action logs exact seven healing before the enemy response',()=>{const r=setup();expect(r.session.playerUse('missing').ok).toBe(false);r.session.playerWait();expect(r.session.log.filter(e=>e.companionSupport)).toHaveLength(0);const before=r.player.health.current;r.session.playerWait();const entry=r.session.log.find(e=>e.companionSupport)!;expect(entry.companionSupport).toEqual({kind:'heal',power:7,actualAmount:7,before,after:before+7,actionNumber:2});expect(entry.text).toContain(`恢复 7 点生命（${before}→${before+7}）`);});
 for(const missing of [0,3])it(`caps ${missing} missing health and keeps the receipt`,()=>{const r=setup('heal',7,1);r.player.health.current=r.player.health.max-missing;r.session.playerWait();expect(r.session.log.find(e=>e.companionSupport)!.companionSupport).toMatchObject({actualAmount:missing,before:r.player.health.max-missing,after:r.player.health.max});});
 it('finishing support reports only remaining enemy health',()=>{const r=setup('attack',99,1);const before=r.encounter.enemy.health;r.session.playerWait();expect(r.session.finalResult?.outcome).toBe('victory');expect(r.session.log.find(e=>e.companionSupport)!.companionSupport).toMatchObject({kind:'attack',power:99,actualAmount:before,before,after:0,actionNumber:1});expect(r.session.log.find(e=>e.companionSupport)!.text).toContain(`造成 ${before} 点伤害`);});
 it('normal attack amount and every-four cadence remain unchanged',()=>{const r=setup('attack',2,4);for(let i=0;i<4&&!r.session.isOver;i++)r.session.playerWait();expect(r.session.log.filter(e=>e.companionSupport)).toHaveLength(1);expect(r.session.log.find(e=>e.companionSupport)!.companionSupport).toMatchObject({actualAmount:2,actionNumber:4});});
 it('immediate player victory settles before support',()=>{const r=setup('attack',9,1);r.encounter.enemy.health=1;const session=new CombatSession({encounter:r.encounter,profile:r.profile,player:r.player,martialArts:r.martialArts,companion:{name:'测试',support:{kind:'attack',power:9,everyPlayerActions:1}}});expect(session.playerUse('skill.jianghu-sanshou').ok).toBe(true);expect(session.finalResult?.outcome).toBe('victory');expect(session.log.filter(e=>e.companionSupport)).toHaveLength(0);});
 it('sessions without a companion retain ordinary turns without support receipts',()=>{const r=setup();const session=new CombatSession({encounter:r.encounter,profile:r.profile,player:r.player,martialArts:r.martialArts});session.playerWait();session.playerWait();expect(session.log.filter(e=>e.companionSupport)).toHaveLength(0);});
 it('retreat and subsequent refused actions never add support',()=>{const r=setup('heal',7,1);r.session.flee();expect(r.session.playerWait().ok).toBe(false);expect(r.session.playerUse('skill.jianghu-sanshou').ok).toBe(false);expect(r.session.log.filter(e=>e.companionSupport)).toHaveLength(0);});
});
