import {readFileSync,writeFileSync,mkdtempSync,mkdirSync,cpSync,rmSync} from 'node:fs';
import {resolve,join,sep} from 'node:path';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {describe,it,expect} from 'vitest';
import {createCharacterState,grantExperience,checkMartialArtEligibility,parseCharacterProfileSet,parseMartialArtSet,parseFactionSet} from '../src/engine/character-progression';
import {createInventoryState,resolveStartingItems,parseItemSet,indexItems,buyItem,equipItem,useConsumable,countItem} from '../src/engine/item-system';
import {createQuestJournal,parseQuestSet,acceptQuest,applyQuestSignal,type QuestUpdateResult} from '../src/engine/quest-system';
import {CombatSession,parseBattleEncounterSet} from '../src/engine/turn-based-combat';
import {parseMeridianSet,unlockMeridianNode,aggregateMeridianEffects,applyMeridianEffects,awardCultivationPoints} from '../src/engine/meridian-system';
import {parseEquipmentForgeSet,craftEquipment} from '../src/engine/equipment-forge';
import {parseMartialArtForgeComponents,craftAndRegisterCustomMartialArt} from '../src/engine/martial-art-forge';
import {parseDialogueSet,validateConversation} from '../src/engine/dialogue-graph';
import {parseKnowledgeNodeSet,parseKnowledgeEdgeSet} from '../src/engine/knowledge-graph';
import {applyDialogueEffects,getVisibleOptions,type DialogueRuntimeContext} from '../src/engine/dialogue-runtime';
import {createFactionMembershipState} from '../src/engine/faction-system';
import {createSocialState} from '../src/engine/social-state';
import {captureSaveSnapshot,parseSaveSnapshot,restoreRunState} from '../src/engine/save-system';
const read=(p:string)=>JSON.parse(readFileSync(new URL('../'+p,import.meta.url),'utf8'));
const knp=parseKnowledgeNodeSet(read('data/base/knowledge_graph/nodes.json')),kep=parseKnowledgeEdgeSet(read('data/base/knowledge_graph/edges.json'));
const pp=parseCharacterProfileSet(read('data/base/characters/round-04-profiles.json')),ap=parseMartialArtSet(read('data/base/skills/round-04-martial-arts.json')),ip=parseItemSet(read('data/base/items/round-06-items.json')),qp=parseQuestSet(read('data/base/quests/round-07-quests.json')),bp=parseBattleEncounterSet(read('data/base/battles/round-05-encounters.json')),mp=parseMeridianSet(read('data/base/meridians/round-23-meridians.json')),fp=parseEquipmentForgeSet(read('data/base/forges/round-24-equipment-forges.json')),cp=parseMartialArtForgeComponents(read('data/base/skills/round-22-components.json')),dp=parseDialogueSet(read('data/base/dialogues/round-03-conversations.json')),fact=parseFactionSet(read('data/base/factions/round-04-factions.json'));
if(!knp.ok||!kep.ok||!pp.ok||!ap.ok||!ip.ok||!qp.ok||!bp.ok||!mp.ok||!fp.ok||!cp.ok||!dp.ok||!fact.ok)throw Error('invalid route data');
const profile=pp.set.profiles[0]!,items=indexItems(ip.set).byId,arts=new Map(ap.set.martialArts.map(a=>[a.id,a])),quests=new Map(qp.set.quests.map(q=>[q.id,q])),encounters=new Map(bp.set.encounters.map(e=>[e.id,e])),factions=new Map(fact.set.factions.map(f=>[f.id,f])),dialogues=new Map(dp.set.conversations.map(d=>[d.id,d])),knowledgeNodes=new Map(knp.data.nodes.map(n=>[n.id,n])),knowledgeEdges=kep.data.edges;
const med=mp.set,forge=fp.set,components=cp.set;
const rawShop=read('data/base/shops/round-06-shops.json').shops[0];
type LedgerRow={action:string;silver:number;level:number;experience:number;health:number;qi:number;details?:unknown};
function run(){const character=createCharacterState(profile,med.resource.initialPoints),inventory=createInventoryState(profile,resolveStartingItems(profile,items).stacks),journal=createQuestJournal(quests),rows:LedgerRow[]=[],custom=new Map();const context:DialogueRuntimeContext={character,inventory,quests,journal,items,social:createSocialState(),speakerNpcId:'char.ye-tingzhou',knownKnowledgeNodeIds:new Set(),knowledgeNodes,knowledgeEdges,factions,martialArts:arts,factionState:createFactionMembershipState(),timeOfDayPeriodId:'period.morning'};const stock=new Map<string,number>(rawShop.stock.map((s:{itemId:string;quantity:number})=>[s.itemId,s.quantity]));const record=(action:string,details?:unknown)=>rows.push({action,silver:inventory.currency,level:character.level,experience:character.experience,health:character.health.current,qi:character.qi.current,details});
 const pay=(update:QuestUpdateResult)=>{for(const reward of update.completed){const gained=grantExperience(profile,character,reward.experience);awardCultivationPoints(character,gained.levelsGained,med.resource);inventory.currency+=reward.currency;record('quest-reward:'+reward.questId,reward);}};
 const buy=(id:string,n=1)=>{expect(buyItem(inventory,stock,items.get(id)!,n).ok,JSON.stringify({id,silver:inventory.currency,recent:rows.slice(-3)})).toBe(true);record('buy:'+id,{quantity:n});};
 const accept=(id:string)=>{const action=acceptQuest(quests,journal,id,new Map(inventory.stacks.map(s=>[s.itemId,countItem(inventory,s.itemId)])));expect(action.ok,id).toBe(true);pay(action.update);};
 const talkQuest=(id:string)=>{accept(id);const q=quests.get(id)!;expect(q.objectives).toHaveLength(1);expect(q.objectives[0]!.kind).toBe('talkToNpc');pay(applyQuestSignal(quests,journal,{type:'npc-talk',npcId:q.objectives[0]!.targetId}));};
 const healOutside=()=>{for(let guard=0;guard<20&&character.health.max-character.health.current>=25;guard++){if(!countItem(inventory,'item.huichun-gao'))buy('item.huichun-gao');expect(useConsumable(inventory,character,items.get('item.huichun-gao')!).ok).toBe(true);record('use:item.huichun-gao');}};
 const fight=(id:string,policy:(s:CombatSession,encounterId:string)=>string)=>{const session=new CombatSession({encounter:encounters.get(id)!,profile,player:character,martialArts:new Map([...arts,...custom]),meridianResourceRules:med.resource});const actions:string[]=[];for(let n=0;n<60&&!session.isOver;n++){const choice=policy(session,id);expect(session.playerUse(choice).ok).toBe(true);actions.push(choice);}record('battle:'+id,{outcome:session.finalResult?.outcome,actions,log:session.log});return session;};
 const equip=(id:string)=>{expect(equipItem({inventory,character,profile,items},items.get(id)!).ok).toBe(true);record('equip:'+id);};
 const unlock=(id:string)=>{expect(unlockMeridianNode({set:med,nodeId:id,character,inventory,items}).ok).toBe(true);applyMeridianEffects(profile,character,aggregateMeridianEffects(med,character.unlockedMeridianNodeIds));record('unlock:'+id);};
 record('new-game');return {character,inventory,journal,rows,custom,context,stock,record,buy,accept,talkQuest,healOutside,fight,equip,unlock,pay};}
const scatter=()=> 'skill.jianghu-sanshou';
function grow(){const r=run();r.buy('item.huichun-gao');r.accept('quest.round-07-medicine-run');deliverMedicine(r);r.talkQuest('quest.r31-peddler-errand');r.talkQuest('quest.r31-roadside-note');r.talkQuest('quest.r31-herbal-inquiry');r.talkQuest('quest.r31-ferry-ledger');r.accept('quest.round-07-clear-alley');expect(r.fight('encounter.alley-blade-bully',scatter).finalResult?.outcome).toBe('victory');r.pay(applyQuestSignal(quests,r.journal,{type:'encounter-victory',encounterId:'encounter.alley-blade-bully'}));for(let n=0;n<3;n++){r.healOutside();expect(r.fight('encounter.r58-market-toll-claimer',scatter).finalResult?.outcome).toBe('victory');}expect(r.character.level).toBe(5);expect(r.character.experience).toBe(283);r.healOutside();return r;}
function optionEffect(r:ReturnType<typeof run>,dialogueId:string,nodeId:string,kind:string,artId?:string){const d=dialogues.get(dialogueId)!;const node=d.nodes.find(n=>n.id===nodeId)!;const option=getVisibleOptions(node,r.context).find(({option})=>option.effects?.some(e=>e.kind===kind&&(!artId||e.kind==='learnMartialArt'&&e.martialArtId===artId)))?.option;expect(option).toBeDefined();const result=applyDialogueEffects(option!.effects??[],r.context);expect(result.ok).toBe(true);r.record('dialogue:'+kind,artId);}
// Round271：送药差事须按F当面交付三份回春膏后才结算（只备料不再自动结案）。
function deliverMedicine(r:ReturnType<typeof run>){r.context.speakerNpcId='char.ma-shangyi';const d=dialogues.get('dlg.ma-shangyi-notice-board')!;const node=d.nodes.find(n=>n.id===d.startNodeId)!;const option=getVisibleOptions(node,r.context).find(({option})=>option.text==='三份回春膏备齐了，这就当面交给你送去。')?.option;expect(option,JSON.stringify(r.rows.slice(-3))).toBeDefined();const result=applyDialogueEffects(option!.effects??[],r.context);expect(result.ok).toBe(true);if(result.ok)r.pay(result.summary.questUpdate);r.record('deliver:medicine-run');}
function prepare(kind:'sword'|'endurance'){const r=grow();if(kind==='sword'){r.context.speakerNpcId='char.ye-tingzhou';optionEffect(r,'dlg.ye-tingzhou-mentor','greet','adjustRelationship');optionEffect(r,'dlg.ye-tingzhou-mentor','greet','joinFaction');optionEffect(r,'dlg.ye-tingzhou-mentor','r32-lessons','learnMartialArt','skill.r32-tingyu-luoyu-jian');r.buy('item.qingtong-bijian');r.buy('item.iron-sand',2);const crafted=craftEquipment({station:{record:forge.stations[0]!,recipes:forge.recipes},recipeId:'forge.recipe.refine-bronze-pen-sword',inventory:r.inventory,items});expect(crafted.ok).toBe(true);r.record('forge',crafted.ok?crafted.result.id:undefined);r.equip('item.qingtong-jian');r.unlock('meridian.qihai');r.unlock('meridian.shouyang');}else{r.context.speakerNpcId='char.wen-suxin';optionEffect(r,'dlg.wen-suxin-mentor','greet','joinFaction');for(const id of ['skill.r32-yunyin-buyun-lu','skill.r32-yunyin-caomu-xinfa'])optionEffect(r,'dlg.wen-suxin-mentor','r32-lessons','learnMartialArt',id);r.buy('item.fanbu-duanhe');r.equip('item.fanbu-duanhe');r.unlock('meridian.qihai');if(!countItem(r.inventory,'item.huichun-gao'))r.buy('item.huichun-gao');r.unlock('meridian.zuyang');const result=craftAndRegisterCustomMartialArt({components,recipe:{intentId:'forge.intent.mend',formId:'forge.form.swift',breathId:'forge.breath.economical'},name:'循息回春',existingArts:[],occupiedIds:new Set(arts.keys()),inventory:r.inventory,learnedArtIds:r.character.martialArtIds,customArts:r.custom});expect(result.ok).toBe(true);r.record('custom-heal',result.ok?result.art.combat:undefined);}r.healOutside();return r;}
describe('Round107 actual conservative growth transactions and encounters',()=>{
 it('same prepared defensive character benefits from observing windup rather than blindly attacking',()=>{const r=prepare('endurance'),start=structuredClone(r.character),encounter=encounters.get('encounter.r101-beacon-raider')!,allArts=new Map([...arts,...r.custom]);const plain=new CombatSession({encounter,profile,player:start,martialArts:allArts});for(let n=0;n<60&&!plain.isOver;n++)plain.playerUse('skill.jianghu-sanshou');const planned=r.fight(encounter.id,s=>{const damage=8+r.character.attributes.force-Math.floor(encounter.enemy.attributes.body/3);if(s.enemyView.health.current<=damage)return 'skill.jianghu-sanshou';if(s.enemyIntent?.includes('守御可卸蓄势')&&r.character.qi.current>=3)return 'skill.r32-yunyin-buyun-lu';if(r.character.health.current<r.character.health.max*0.7&&r.character.qi.current>=2)return 'custom-art.1';return 'skill.jianghu-sanshou';});expect(planned.finalResult?.outcome).toBe('victory');expect(plain.finalResult?.outcome).toBe('victory');expect(r.character.health.current).toBeGreaterThan(start.health.current);expect(r.character.qi.current).toBeLessThan(start.qi.current);if(process.env.WUXIA_R107_REPORT==='1')writeFileSync(new URL('../iterations/round-107/response-comparison.json',import.meta.url),JSON.stringify({scope:'Same prepared state, headless real CombatSession; both strategies remain viable, observing cues trades qi/turns for health.',plain:{health:start.health.current,qi:start.qi.current,log:plain.log},planned:r.rows.at(-1)},null,2)+'\n');});
 it.each(['sword','endurance'] as const)('%s: real rewards, qualification, expenditure and challenge ledger',kind=>{const r=prepare(kind);const policy=(s:CombatSession,encounterId:string)=>{if(kind==='sword')return r.character.qi.current>=3?'skill.r32-tingyu-luoyu-jian':'skill.jianghu-sanshou';const attackDamage=8+r.character.attributes.force-Math.floor(encounters.get(encounterId)!.enemy.attributes.body/3);if(s.enemyView.health.current<=attackDamage)return 'skill.jianghu-sanshou';if(s.enemyIntent?.includes('未守御伤害')&&r.character.qi.current>=3)return 'skill.r32-yunyin-buyun-lu';if(r.character.health.current<r.character.health.max*0.7&&r.character.qi.current>=2)return 'custom-art.1';return 'skill.jianghu-sanshou';};for(const id of ['encounter.r58-market-toll-claimer','encounter.r101-beacon-raider']){r.healOutside();expect(r.fight(id,policy).finalResult?.outcome,JSON.stringify(r.rows.at(-1))).toBe('victory');}expect(r.inventory.currency).toBeGreaterThanOrEqual(0);expect(r.context.factionState.membership?.factionId).toBe(kind==='sword'?'faction.tingyu-jiange':'faction.yunyin-shanzhuang');if(process.env.WUXIA_R107_REPORT==='1')writeFileSync(new URL(`../iterations/round-107/${kind}-ledger.json`,import.meta.url),JSON.stringify({scope:'Actual headless transactions and CombatSession, not keyboard travel. Starting 120 silver; excludes achievement income. Three repeatable market bouts supply XP; healing purchases are paid.',rows:r.rows},null,2)+'\n');});
 it('unprepared new character loses the northern challenge and receives authored recovery',()=>{const r=run();const session=r.fight('encounter.r101-beacon-raider',scatter);expect(session.finalResult?.outcome).toBe('defeat');expect(r.character.experience).toBe(0);expect(r.character.health.current).toBe(Math.ceil(r.character.health.max*0.6));});
 it('level 2 is insufficient for both route entry arts on this profile',()=>{const r=run();grantExperience(profile,r.character,40);expect(r.character.level).toBe(2);for(const id of ['skill.r32-tingyu-luoyu-jian','skill.r32-yunyin-buyun-lu','skill.r32-yunyin-caomu-xinfa'])expect(checkMartialArtEligibility(arts.get(id)!,{level:r.character.level,attributes:r.character.attributes,factionId:arts.get(id)!.factionIds[0]!}).eligible).toBe(false);});
 it('level 4 scribe qualifies for Rain Sevenfold through the purchasable willow judge pen',()=>{const r=run();grantExperience(profile,r.character,180);expect(r.character.level).toBe(4);expect(r.character.attributes.agility).toBe(10);expect(r.character.attributes.insight).toBe(11);r.context.factionState.membership={factionId:'faction.tingyu-jiange',masterNpcId:'char.ye-tingzhou'};const art=arts.get('skill.r32-tingyu-luoyu-jian')!;expect(checkMartialArtEligibility(art,{level:4,attributes:r.character.attributes,factionId:'faction.tingyu-jiange'}).eligible).toBe(false);r.buy('item.r32.willow-switch-sword');r.equip('item.r32.willow-switch-sword');expect(r.character.attributes.agility).toBe(11);expect(checkMartialArtEligibility(art,{level:4,attributes:r.character.attributes,factionId:'faction.tingyu-jiange'}).eligible).toBe(true);const lesson=dialogues.get('dlg.ye-tingzhou-mentor')!.nodes.find(n=>n.id==='r32-lessons')!;expect(getVisibleOptions(lesson,r.context).some(v=>v.option.effects?.some(e=>e.kind==='learnMartialArt'&&e.martialArtId===art.id))).toBe(true);});
 it.each(['sword','endurance'] as const)('%s preparations persist through v1 snapshot and restored next battle',kind=>{const r=prepare(kind);const snapshot=captureSaveSnapshot({displayName:'路线检查',mapResourceId:'map.round-10-mist-ferry',playerCol:12,playerRow:4,character:r.character,inventory:r.inventory,journal:r.journal,social:r.context.social,factionMembership:r.context.factionState.membership,customMartialArts:r.custom,shopStocks:new Map([[rawShop.id,r.stock]]),completedEncounters:new Set(['encounter.alley-blade-bully']),completedRegionalEvents:new Set(),knownKnowledgeNodeIds:new Set(),elapsedGameMinutes:20,worldSeed:107});expect(parseSaveSnapshot(JSON.parse(JSON.stringify(snapshot))).ok).toBe(true);const restored=restoreRunState({snapshot,profile,items,quests,shops:new Map([[rawShop.id,{record:rawShop,stock:rawShop.stock}]])});expect(restored.character.unlockedMeridianNodeIds).toEqual(r.character.unlockedMeridianNodeIds);expect(restored.inventory.currency).toBe(r.inventory.currency);expect(restored.character.martialArtIds).toEqual(r.character.martialArtIds);expect(restored.customMartialArts).toHaveLength(kind==='sword'?0:1);const session=new CombatSession({encounter:encounters.get('encounter.r58-market-toll-claimer')!,profile,player:restored.character,martialArts:new Map([...arts,...restored.customMartialArts.map(a=>[a.id,a] as const)])});expect(session.enemyIntent).toContain('先护');});
 it('two in-game preparation chains are visible before membership and preserve original dialogue graph',()=>{for(const id of ['dlg.ye-tingzhou-mentor','dlg.wen-suxin-mentor']){const d=dialogues.get(id)!,r=run();expect(validateConversation(d)).toEqual([]);const options=getVisibleOptions(d.nodes.find(n=>n.id===d.startNodeId)!,r.context);expect(options.some(o=>o.option.nextNodeId?.startsWith('r107-'))).toBe(true);expect(d.nodes.filter(n=>n.id.startsWith('r107-'))).toHaveLength(3);}});
 it('incremental authoring replays twice in verified temporary workspace without touching the checkout',()=>{const root=resolve(mkdtempSync(join(tmpdir(),'wuxia-r107-')));expect(root.startsWith(resolve(tmpdir())+sep)).toBe(true);try{mkdirSync(join(root,'data/base'),{recursive:true});cpSync(resolve('data/base/battles'),join(root,'data/base/battles'),{recursive:true});cpSync(resolve('data/base/dialogues'),join(root,'data/base/dialogues'),{recursive:true});for(let i=0;i<2;i++)execFileSync(process.execPath,[resolve('scripts/deepen-round107-combat-routes.mjs')],{cwd:root});for(const file of ['battles/round-05-encounters.json','dialogues/round-03-conversations.json'])expect(readFileSync(join(root,'data/base',file),'utf8')).toBe(readFileSync(resolve('data/base',file),'utf8'));}finally{expect(root.startsWith(resolve(tmpdir())+sep)).toBe(true);rmSync(root,{recursive:true,force:true});}});
});
