import {readFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';import {describe,it,expect} from 'vitest';import {parseDialogueSet} from '../src/engine/dialogue-graph';
const read=(p:string)=>JSON.parse(readFileSync('data/base/'+p,'utf8'));
const raw=read('dialogues/round-94-frontiers-conversations.json');const talk=raw.conversations.find((d:{id:string})=>d.id==='dlg.r94-shen-wenqiu');const close=talk.nodes.find((n:{id:string})=>n.id==='r101-north-close');
describe('Round169 sea preparation remains actionable and evidence bounded',()=>{
 it('parses and preserves the stage-answer evidence limits',()=>{expect(parseDialogueSet(raw).ok).toBe(true);expect(close.text).toContain('不认作者');expect(close.text).toContain('备齐不等于已传航');expect(close.text).toContain('亲查');});
 it('matches real public and limited supplies and merchant',()=>{expect(close.text).toContain('厚蚌壳片2片');expect(close.text).toContain('清心丸1份');const stock=read('shops/round-83-east-coast-shops.json').shops.find((s:{npcId:string})=>s.npcId==='char.r83-jin-yunfan').stock;expect(stock).toContainEqual({itemId:'item.r32.clam-shell',quantity:4});const ji=read('dialogues/round-97-lanxin-reef-conversations.json').conversations.find((d:{id:string})=>d.id==='dlg.r97-ji-wuchao');const options=ji.nodes.flatMap((n:{options?:unknown[]})=>n.options??[]);expect(options.some((o:{effects?:{kind:string,itemId?:string,quantity?:number}[]})=>o.effects?.some(e=>e.kind==='takeItem'&&e.itemId==='item.r32.clam-shell'&&e.quantity===2))).toBe(true);});
 it('does not award supplies or choose sea outcome on north closure',()=>{const entry=talk.nodes[0].options.find((o:{nextNodeId:string})=>o.nextNodeId===close.id);expect(entry.effects).toEqual([{kind:'discoverKnowledgeNode',nodeId:'event.r101-north-close'}]);});
 it('shared author preserves full current dialogue data',()=>{const s=execFileSync(process.execPath,['--input-type=module','-e',"import {readFileSync} from 'node:fs';import {deepenNorthDialogues} from './scripts/lib/round101-north-content.mjs';const d=JSON.parse(readFileSync('data/base/dialogues/round-94-frontiers-conversations.json','utf8'));deepenNorthDialogues(d);console.log(JSON.stringify(d));"],{encoding:'utf8'});expect(JSON.parse(s)).toEqual(raw);});
});
