import {readFileSync} from 'node:fs';
import {describe,expect,it} from 'vitest';
import {parseQuestSet,createQuestJournal,acceptQuest,applyQuestSignal,reconcileQuestFacts,type QuestData} from '../src/engine/quest-system';
import {parseDialogueSet,validateConversation,type DialogueData} from '../src/engine/dialogue-graph';
import {applyDialogueEffects,getVisibleOptions,assembleDialogueReferences,type DialogueRuntimeContext} from '../src/engine/dialogue-runtime';
import {parseCharacterProfileSet,createCharacterState,parseMartialArtSet} from '../src/engine/character-progression';
import {parseItemSet,indexItems,createInventoryState,countItem} from '../src/engine/item-system';
import {createSocialState,getRelationship} from '../src/engine/social-state';
import {createFactionMembershipState} from '../src/engine/faction-system';
import {captureSaveSnapshot,parseSaveSnapshot,planSnapshotRestore,restoreRunState} from '../src/engine/save-system';
import {regionEventConditionsMet,type RegionEventData} from '../src/engine/world-map';
import type {KnowledgeNodeData} from '../src/engine/knowledge-graph';
import {deepenSeaQuests,deepenSeaDialogues,seaQuestIds} from '../scripts/lib/round102-sea-content.mjs';
const read=(p:string)=>JSON.parse(readFileSync(new URL('../data/base/'+p,import.meta.url),'utf8'));
const names=['round-83-east-coast','round-84-windward-isle','round-85-tide-isle','round-97-lanxin-reef'];
const DG='dlg.r83-gu-chaosheng-tide-line',DJ='dlg.r97-ji-wuchao',DY='dlg.r97-yu-xingcha',DC='dlg.r85-cen-yinjiao-reef',DR='dlg.r84-ruan-huilan-lantern';
const GU='char.r83-gu-chaosheng',CEN='char.r85-cen-yinjiao',JI='char.r97-ji-wuchao',YU='char.r97-yu-xingcha';
function run(){
 const p=parseCharacterProfileSet(read('characters/round-04-profiles.json'));if(!p.ok)throw Error(p.errors.join());const profile=p.set.profiles[0]!;
 const quests=new Map<string,QuestData>(),dialogues=new Map<string,DialogueData>(),npcIds=new Set<string>();
 for(const name of names){const q=parseQuestSet(read('quests/'+name+'-quests.json')),d=parseDialogueSet(read('dialogues/'+name+'-conversations.json'));if(!q.ok||!d.ok)throw Error('海路资料解析失败');for(const e of q.set.quests)quests.set(e.id,e);for(const e of d.set.conversations)dialogues.set(e.id,e);}
 // Include predecessor because the real coastal battle quest requires it.
 const predecessor=parseQuestSet(read('quests/round-82-east-coast-quests.json'));if(!predecessor.ok)throw Error(predecessor.errors.join());for(const q of predecessor.set.quests)quests.set(q.id,q);
 for(const n of ['round-83-east-coast-npcs','round-84-windward-isle-npcs','round-85-tide-isle-npcs','round-97-lanxin-reef-npcs'])for(const npc of read('characters/'+n+'.json').npcs)npcIds.add(npc.id);
 const itemList=['items/round-06-items.json','items/round-83-east-coast-items.json'].flatMap(path=>{const p=parseItemSet(read(path));if(!p.ok)throw Error(p.errors.join());return p.set.items;});const items=indexItems({items:itemList}).byId;
 const art=parseMartialArtSet(read('skills/round-04-martial-arts.json'));if(!art.ok)throw Error(art.errors.join());
 const ctx:DialogueRuntimeContext={quests,journal:createQuestJournal(quests),items,inventory:createInventoryState(profile,[{itemId:'item.huichun-gao',quantity:4},{itemId:'item.qingxin-wan',quantity:4},{itemId:'item.r83-sea-salt-ointment',quantity:4},{itemId:'item.r32.clam-shell',quantity:4}]),social:createSocialState(),speakerNpcId:GU,knownKnowledgeNodeIds:new Set(),knowledgeNodes:new Map<string,KnowledgeNodeData>(read('knowledge_graph/nodes.json').nodes.map((n:KnowledgeNodeData)=>[n.id,n])),character:createCharacterState(profile),factions:new Map(),martialArts:new Map(art.set.martialArts.map(a=>[a.id,a])),factionState:createFactionMembershipState(),timeOfDayPeriodId:'period.night'};ctx.social.renown=10;
 return {ctx,profile,dialogues,npcIds};
}
type Run=ReturnType<typeof run>;
const node=(r:Run,d:string,id:string)=>r.dialogues.get(d)!.nodes.find(n=>n.id===id)!;
const visible=(r:Run,d:string,id='greet')=>getVisibleOptions(node(r,d,id),r.ctx);
function choose(r:Run,d:string,id:string,target:string){const v=visible(r,d,id).find(v=>v.option.nextNodeId===target);expect(v).toBeDefined();expect(applyDialogueEffects(v!.option.effects??[],r.ctx).ok).toBe(true);}
const complete=(r:Run,id:string)=>{r.ctx.journal.states.get(id)!.status='completed';reconcileQuestFacts(r.ctx.quests,r.ctx.journal,{});};
function capture(r:Run){return captureSaveSnapshot({displayName:'海路测试',mapResourceId:'map.round-97-lanxin-isle',playerCol:50,playerRow:50,character:r.ctx.character!,inventory:r.ctx.inventory!,journal:r.ctx.journal,social:r.ctx.social,shopStocks:new Map(),completedEncounters:new Set(),completedRegionalEvents:new Set(),knownKnowledgeNodeIds:r.ctx.knownKnowledgeNodeIds,elapsedGameMinutes:10,worldSeed:123});}
const refs=(r:Run)=>({profileIds:new Set([r.profile.id]),profileRecords:new Map([[r.profile.id,r.profile]]),mapResourceId:'map.round-97-lanxin-isle',isWalkableCell:()=>true,isCellOccupied:()=>false,itemIds:new Set(r.ctx.items.keys()),itemRecords:r.ctx.items,martialArtIds:new Set(r.ctx.martialArts.keys()),questIds:new Set(r.ctx.quests.keys()),questObjectiveIds:new Map([...r.ctx.quests].map(([id,q])=>[id,new Set(q.objectives.map(o=>o.id))])),questRecords:r.ctx.quests,encounterIds:new Set<string>(),shopIds:new Set<string>(),npcIds:r.npcIds,knowledgeNodeIds:new Set(r.ctx.knowledgeNodes.keys())});
describe('Round102 shipped sea chapter',()=>{
 it('runs predecessor and six shipped quests through actual journal transitions to chapter closure',()=>{
  const r=run(),rewardIds:string[]=[];let currency=0;
  for(const id of ['quest.r82-follow-the-tide',...seaQuestIds]){
   const accepted=acceptQuest(r.ctx.quests,r.ctx.journal,id,undefined,{knownKnowledgeNodeIds:r.ctx.knownKnowledgeNodeIds});expect(accepted.ok,id).toBe(true);
   const q=r.ctx.quests.get(id)!;
   for(const objective of q.objectives){
    const signal=objective.kind==='discoverKnowledge'?{type:'knowledge-discovery' as const,nodeId:objective.targetId}:objective.kind==='defeatEncounter'?{type:'encounter-victory' as const,encounterId:objective.targetId}:{type:'npc-talk' as const,npcId:objective.targetId};
    if(signal.type==='knowledge-discovery')r.ctx.knownKnowledgeNodeIds.add(signal.nodeId);
    const update=applyQuestSignal(r.ctx.quests,r.ctx.journal,signal);
    for(const reward of update.completed){rewardIds.push(reward.questId);currency+=reward.currency;for(const knowledge of reward.discoverKnowledgeNodeIds??[])r.ctx.knownKnowledgeNodeIds.add(knowledge);}
   }
   expect(r.ctx.journal.states.get(id)!.status,id).toBe('completed');
  }
  expect(rewardIds).toEqual(['quest.r82-follow-the-tide',...seaQuestIds]);expect(currency).toBe(232);
  choose(r,DG,'greet','r102-supply-choice');choose(r,DG,'r102-supply-choice','r102-shore-aid');choose(r,DJ,'greet','r102-pilot-choice');choose(r,DJ,'r102-pilot-choice','r102-pilot-public');choose(r,DY,'greet','r102-sea-crosscheck');choose(r,DY,'greet','r102-sea-close');expect(r.ctx.knownKnowledgeNodeIds.has('event.r102-sea-close')).toBe(true);
 });
 it('all dialogue options assemble with real quest/item/NPC/knowledge references',()=>{const r=run();for(const d of r.dialogues.values())expect(validateConversation(d),d.id).toEqual([]);expect(assembleDialogueReferences({conversations:r.dialogues,quests:r.ctx.quests,items:r.ctx.items,placedNpcIds:r.npcIds,knowledgeNodeIds:new Set(r.ctx.knowledgeNodes.keys()),factionIds:new Set(),martialArtIds:new Set(r.ctx.martialArts.keys()),timeOfDayPeriodIds:new Set(['period.night'])}).warnings).toEqual([]);});
 it.each(['quest.r85-low-tide-channel','quest.r97-tide-ledger','quest.r97-beacon-relight'])('%s needs investigation before a fresh report',id=>{const r=run();if(id==='quest.r97-beacon-relight')complete(r,'quest.r97-tide-ledger');expect(acceptQuest(r.ctx.quests,r.ctx.journal,id).ok).toBe(true);const q=r.ctx.quests.get(id)!;expect(q.orderedObjectives).toBe(true);expect(applyQuestSignal(r.ctx.quests,r.ctx.journal,{type:'npc-talk',npcId:q.giverNpcId}).completed).toHaveLength(0);expect(r.ctx.journal.states.get(id)!.objectiveCounts.get(q.objectives.at(-1)!.id)).toBe(0);for(const o of q.objectives.filter(o=>o.kind==='discoverKnowledge'))applyQuestSignal(r.ctx.quests,r.ctx.journal,{type:'knowledge-discovery',nodeId:o.targetId});expect(applyQuestSignal(r.ctx.quests,r.ctx.journal,{type:'npc-talk',npcId:q.giverNpcId}).completed.map(q=>q.questId)).toEqual([id]);expect(applyQuestSignal(r.ctx.quests,r.ctx.journal,{type:'npc-talk',npcId:q.giverNpcId}).completed).toHaveLength(0);});
 it('lantern already known before pilot acceptance avoids an extra round trip',()=>{const r=run();complete(r,'quest.r97-tide-ledger');r.ctx.knownKnowledgeNodeIds.add('place.r97-lantern-terrace');expect(acceptQuest(r.ctx.quests,r.ctx.journal,'quest.r97-beacon-relight',undefined,{knownKnowledgeNodeIds:r.ctx.knownKnowledgeNodeIds}).ok).toBe(true);reconcileQuestFacts(r.ctx.quests,r.ctx.journal,{knownKnowledgeNodeIds:r.ctx.knownKnowledgeNodeIds});expect(r.ctx.journal.states.get('quest.r97-beacon-relight')!.objectiveCounts.get('objective.r97-copy-lantern-verse')).toBe(1);expect(applyQuestSignal(r.ctx.quests,r.ctx.journal,{type:'npc-talk',npcId:YU}).completed[0]?.currency).toBe(48);});
 it.each(['shore-aid','keeper-aid'])('supply %s pays once and echoes at three other people',branch=>{const r=run();complete(r,'quest.r83-night-channel');choose(r,DG,'greet','r102-supply-choice');choose(r,DG,'r102-supply-choice','r102-'+branch);const shore=branch==='shore-aid';expect(countItem(r.ctx.inventory!,shore?'item.r83-sea-salt-ointment':'item.huichun-gao')).toBe(3);expect(getRelationship(r.ctx.social,GU)).toBe(shore?4:-3);expect(getRelationship(r.ctx.social,CEN)).toBe(shore?-3:4);expect(r.ctx.social.renown).toBe(shore?12:9);expect(visible(r,DG).some(v=>v.option.nextNodeId==='r102-supply-choice')).toBe(false);expect(visible(r,DG,'r102-supply-choice').filter(v=>v.option.effects?.length)).toHaveLength(0);for(const d of [DR,DC,DJ])expect(visible(r,d).some(v=>v.option.nextNodeId==='r102-echo-'+branch)).toBe(true);});
 it.each(['pilot-public','pilot-crew'])('pilot %s has distinct resource costs and social consequences',branch=>{const r=run();complete(r,'quest.r97-tide-ledger');choose(r,DJ,'greet','r102-pilot-choice');choose(r,DJ,'r102-pilot-choice','r102-'+branch);const pub=branch==='pilot-public';expect(countItem(r.ctx.inventory!,pub?'item.r32.clam-shell':'item.qingxin-wan')).toBe(pub?2:3);expect(getRelationship(r.ctx.social,JI)).toBe(pub?4:-4);expect(getRelationship(r.ctx.social,YU)).toBe(pub?-4:4);expect(r.ctx.social.renown).toBe(pub?13:8);expect(visible(r,DJ,'r102-pilot-choice').filter(v=>v.option.effects?.length)).toHaveLength(0);for(const d of [DG,DY])expect(visible(r,d).some(v=>v.option.nextNodeId==='r102-echo-'+branch)).toBe(true);});
 it('missing goods hides and refuses all paid alternatives without partial mutation',()=>{const r=run();r.ctx.inventory!.stacks=[];for(const [d,id]of [[DG,'r102-supply-choice'],[DJ,'r102-pilot-choice']]){expect(visible(r,d!,id!).filter(v=>v.option.effects?.length)).toHaveLength(0);for(const o of node(r,d!,id!).options!.filter(o=>o.effects?.length))expect(applyDialogueEffects(o.effects!,r.ctx).ok).toBe(false);}expect(r.ctx.knownKnowledgeNodeIds.size).toBe(0);expect(r.ctx.social.renown).toBe(10);expect(getRelationship(r.ctx.social,YU)).toBe(0);});
 it('requires all six real completions, both paid decisions and crosscheck to close',()=>{const r=run();for(const id of seaQuestIds.slice(0,-1))complete(r,id);expect(visible(r,DY).some(v=>v.option.nextNodeId==='r102-sea-crosscheck')).toBe(false);complete(r,seaQuestIds.at(-1)!);choose(r,DY,'greet','r102-sea-crosscheck');expect(visible(r,DY).some(v=>v.option.nextNodeId==='r102-sea-close')).toBe(false);choose(r,DG,'r102-supply-choice','r102-keeper-aid');choose(r,DJ,'r102-pilot-choice','r102-pilot-crew');choose(r,DY,'greet','r102-sea-close');expect(r.ctx.knownKnowledgeNodeIds.has('event.r102-sea-close')).toBe(true);expect(visible(r,DY).some(v=>v.option.nextNodeId==='r102-sea-close')).toBe(false);});
 it.each([['shore-aid','pilot-public'],['keeper-aid','pilot-crew']])('v1 roundtrip preserves %s and %s costs, flags and later echoes',(supply,pilot)=>{const r=run();complete(r,'quest.r83-night-channel');complete(r,'quest.r97-tide-ledger');choose(r,DG,'r102-supply-choice','r102-'+supply);choose(r,DJ,'r102-pilot-choice','r102-'+pilot);const currency=r.ctx.inventory!.currency;const parsed=parseSaveSnapshot(JSON.parse(JSON.stringify(capture(r))));expect(parsed.ok).toBe(true);if(!parsed.ok)return;const plan=planSnapshotRestore(parsed.snapshot,refs(r));expect(plan.ok).toBe(true);if(!plan.ok)return;expect(plan.warnings).toEqual([]);const state=restoreRunState({snapshot:plan.snapshot,profile:r.profile,items:r.ctx.items,quests:r.ctx.quests,shops:new Map()});r.ctx.inventory=state.inventory;r.ctx.social=state.social;r.ctx.journal=state.journal;r.ctx.knownKnowledgeNodeIds=new Set(state.knownKnowledgeNodeIds);expect(r.ctx.inventory.currency).toBe(currency);expect(countItem(r.ctx.inventory,supply==='shore-aid'?'item.r83-sea-salt-ointment':'item.huichun-gao')).toBe(3);expect(countItem(r.ctx.inventory,pilot==='pilot-public'?'item.r32.clam-shell':'item.qingxin-wan')).toBe(pilot==='pilot-public'?2:3);expect(visible(r,DC).some(v=>v.option.nextNodeId==='r102-echo-'+supply)).toBe(true);expect(visible(r,DY).some(v=>v.option.nextNodeId==='r102-echo-'+pilot)).toBe(true);expect(visible(r,DJ).some(v=>v.option.nextNodeId==='r102-pilot-choice')).toBe(false);});
 it('real reef low tide and coastal twilight gates remain distinct from unconstrained tide stone',()=>{const events=read('world/world-map.json').events as RegionEventData[];const reef=events.find(e=>e.id==='event.r85-reef-channel')!,coast=events.find(e=>e.discoverKnowledgeNodeId==='place.r83-night-channel')!,stone=events.find(e=>e.id==='event.r97-tide-mark-stone')!;for(const tideId of ['tide.low','tide.high'])expect(regionEventConditionsMet(reef,{knownKnowledgeNodeIds:new Set(),periodId:'period.dusk',weatherId:'weather.clear',tideId})).toBe(tideId==='tide.low');for(const periodId of ['period.morning','period.dusk','period.night'])expect(regionEventConditionsMet(coast,{knownKnowledgeNodeIds:new Set(['place.r83-net-shoals']),weatherId:'weather.clear',periodId})).toBe(periodId!=='period.morning');expect(stone.conditions).toBeUndefined();});
 it('shipped data is stable under the shared source transformations and generators use them',()=>{for(const name of names){const quests=read('quests/'+name+'-quests.json'),dialogues=read('dialogues/'+name+'-conversations.json');expect(deepenSeaQuests(structuredClone(quests))).toEqual(quests);expect(deepenSeaDialogues(structuredClone(dialogues))).toEqual(dialogues);}for(const name of ['generate-round83-east-coast-content','generate-round84-windward-isle','generate-round85-tide-isle','generate-round97-lanxin-isle']){const source=readFileSync(new URL('../scripts/'+name+'.mjs',import.meta.url),'utf8');expect(source).toContain("'./lib/round102-sea-content.mjs'");expect(source).toMatch(/write(?:New)?Json\([^\n]+deepenSeaDialogues\(/);expect(source).toMatch(/write(?:New)?Json\([^\n]+deepenSeaQuests\(/);}});
 it('route coordinates and schedule hints are facts from the active world',()=>{const r=run(),events=read('world/world-map.json').events;for(const [id,pair]of [['event.r97-tide-mark-stone','(58,22)'],['event.r97-lantern-terrace','(46,76)']]){const e=events.find((e:RegionEventData)=>e.id===id);expect(pair).toBe(`(${e.col},${e.row})`);expect(r.dialogues.get(DJ)!.nodes.some(n=>n.text.includes(pair!))).toBe(true);}const npc=read('characters/round-97-lanxin-reef-npcs.json').npcs[0];for(const period of ['period.morning','period.midday']){const p=npc.schedule.find((s:{periodId:string})=>s.periodId===period).position;expect(node(r,DJ,'accepted').text).toContain(`(${p.col},${p.row})`);}const gates=read('world/world-map.json').transitions;for(const id of ['gate.r84-east-coast-to-windward-isle','gate.r85-windward-isle-to-tide-isle','gate.r97-tide-to-lanxin','gate.r97-pilot-to-east']){const g=gates.find((g:{id:string})=>g.id===id);expect([...r.dialogues.values()].some(d=>d.nodes.some(n=>n.text.includes(`(${g.from.col},${g.from.row})`)))).toBe(true);}});
});
