import {readFileSync,readdirSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {parseQuestSet,createQuestJournal,type QuestData} from '../src/engine/quest-system';
import {parseDialogueSet,validateConversation,type DialogueData} from '../src/engine/dialogue-graph';
import {applyDialogueEffects,getVisibleOptions,type DialogueRuntimeContext} from '../src/engine/dialogue-runtime';
import {parseCharacterProfileSet,createCharacterState,parseMartialArtSet} from '../src/engine/character-progression';
import {parseItemSet,indexItems,createInventoryState} from '../src/engine/item-system';
import {createSocialState,getRelationship,npcKnows} from '../src/engine/social-state';
import {createFactionMembershipState} from '../src/engine/faction-system';
import {parseCompanionSet,assembleCompanions,resolveCompanionStance} from '../src/engine/companion-system';
import {captureSaveSnapshot,parseSaveSnapshot,planSnapshotRestore,restoreRunState} from '../src/engine/save-system';
import type {KnowledgeNodeData} from '../src/engine/knowledge-graph';
import {people,relays,stanceRules,deepenPeopleConversation} from '../scripts/lib/round105-people-content.mjs';
const read=(p:string)=>JSON.parse(readFileSync(new URL('../data/base/'+p,import.meta.url),'utf8'));
function fixture(){
 const parsed=parseCharacterProfileSet(read('characters/round-04-profiles.json'));if(!parsed.ok)throw Error(parsed.errors.join());const profile=parsed.set.profiles[0]!;
 const quests=new Map<string,QuestData>();for(const file of readdirSync(new URL('../data/base/quests/',import.meta.url)).filter(f=>f.endsWith('.json'))){const p=parseQuestSet(read('quests/'+file));if(!p.ok)throw Error(p.errors.join());for(const q of p.set.quests)quests.set(q.id,q);}
 const dialogues=new Map<string,DialogueData>();for(const person of people){const p=parseDialogueSet(read('dialogues/'+person.file));if(!p.ok)throw Error(p.errors.join());for(const d of p.set.conversations)dialogues.set(d.id,d);}
 const pi=parseItemSet(read('items/round-06-items.json'));if(!pi.ok)throw Error(pi.errors.join());const items=indexItems(pi.set).byId;
 const pa=parseMartialArtSet(read('skills/round-04-martial-arts.json'));if(!pa.ok)throw Error(pa.errors.join());
 const pc=parseCompanionSet(read('companions/round-19-companions.json'));if(!pc.ok)throw Error(pc.errors.join());const companion=pc.set.companions[0]!;
 const ctx:DialogueRuntimeContext={quests,journal:createQuestJournal(quests),items,inventory:createInventoryState(profile,[]),social:createSocialState(),speakerNpcId:people[0]!.npcId,knownKnowledgeNodeIds:new Set(),knowledgeNodes:new Map<string,KnowledgeNodeData>(read('knowledge_graph/nodes.json').nodes.map((n:KnowledgeNodeData)=>[n.id,n])),character:createCharacterState(profile),factions:new Map(),martialArts:new Map(pa.set.martialArts.map(a=>[a.id,a])),factionState:createFactionMembershipState(),timeOfDayPeriodId:'period.midday'};
 const visible=(id:string)=>{const d=dialogues.get(id)!;return getVisibleOptions(d.nodes.find(n=>n.id===d.startNodeId)!,ctx);};
 const choose=(id:string,next:string)=>{const v=visible(id).find(v=>v.option.nextNodeId===next);expect(v,next).toBeDefined();expect(applyDialogueEffects(v!.option.effects??[],ctx).ok).toBe(true);};
 return {ctx,profile,dialogues,companion,visible,choose};
}
describe('Round105 shipped people and companion stances',()=>{
 for(const person of people)it(person.npcId+' has exclusive pre/active/completed concerns and repeatable source authoring',()=>{
  const r=fixture(),d=r.dialogues.get(person.dialogueId)!;r.ctx.speakerNpcId=person.npcId;
  for(const [status,suffix] of [['locked','before'],['offered','before'],['active','active'],['completed','after']] as const){r.ctx.journal.states.get(person.questId)!.status=status;const v=r.visible(d.id).filter(v=>/^r105-(before|active|after)$/.test(v.option.nextNodeId??''));expect(v).toHaveLength(1);expect(v[0]!.option.nextNodeId).toBe('r105-'+suffix);expect(v[0]!.option.effects??[]).toEqual([]);expect(d.nodes.find(n=>n.id==='r105-'+suffix)!.text).toBe(person[suffix]);}
  expect(validateConversation(d)).toEqual([]);expect(deepenPeopleConversation(structuredClone(d))).toEqual(d);
 });
 for(const relay of relays)for(const [index,variant] of relay.variants.entries())it(relay.key+' variant '+index+' actually shares two memories, changes relationship once and restores v1',()=>{
  const r=fixture();r.ctx.speakerNpcId=relay.sourceNpcId;r.ctx.knownKnowledgeNodeIds.add(relay.sourceGate);
  if(relay.sourceQuestId)r.ctx.journal.states.get(relay.sourceQuestId)!.status='completed';
  const source='r105-'+relay.key+'-source'+(relay.sourceSharedAny?'-0':'');
  if(relay.sourceSharedAny){const flag=relay.sourceSharedAny[0]!;r.ctx.knownKnowledgeNodeIds.add(flag);expect(r.visible(relay.sourceDialogueId).some(v=>v.option.nextNodeId===source)).toBe(false);const share=r.visible(relay.sourceDialogueId).find(v=>v.option.effects?.some(e=>e.kind==='shareKnowledgeNode'&&e.nodeId===flag))!;expect(share).toBeDefined();expect(applyDialogueEffects(share.option.effects!,r.ctx).ok).toBe(true);}
  r.choose(relay.sourceDialogueId,source);const message='event.r105-'+relay.key+'-message',delivered='event.r105-'+relay.key+'-delivered';expect(npcKnows(r.ctx.social,relay.targetNpcId,message)).toBe(false);
  r.ctx.speakerNpcId=relay.targetNpcId;r.ctx.knownKnowledgeNodeIds.add(variant.flag);const receive='r105-'+relay.key+'-receive-'+index;
  expect(r.visible(relay.targetDialogueId).some(v=>v.option.nextNodeId===receive)).toBe(false);r.ctx.journal.states.get(relay.targetQuestId)!.status='completed';r.choose(relay.targetDialogueId,receive);
  expect(npcKnows(r.ctx.social,relay.targetNpcId,message)).toBe(true);expect(npcKnows(r.ctx.social,relay.targetNpcId,variant.flag)).toBe(true);expect(getRelationship(r.ctx.social,relay.targetNpcId)).toBe(variant.delta);expect(r.ctx.knownKnowledgeNodeIds.has(delivered)).toBe(true);
  expect(r.visible(relay.targetDialogueId).filter(v=>v.option.nextNodeId?.startsWith('r105-'+relay.key+'-receive-'))).toHaveLength(0);r.choose(relay.targetDialogueId,'r105-'+relay.key+'-received');expect(getRelationship(r.ctx.social,relay.targetNpcId)).toBe(variant.delta);
  const followup='r136-'+relay.key+'-followup-'+index;
  const repeated=r.visible(relay.targetDialogueId).filter(v=>v.option.nextNodeId?.startsWith('r136-'+relay.key+'-followup-'));
  expect(repeated.map(v=>v.option.nextNodeId)).toEqual([followup]);
  const beforeRepeat=JSON.stringify(captureSaveSnapshot({displayName:'复谈',now:()=>new Date('2026-01-01T00:00:00Z'),mapResourceId:'map.round-01-grid',playerCol:1,playerRow:1,character:r.ctx.character!,inventory:r.ctx.inventory!,journal:r.ctx.journal,social:r.ctx.social,shopStocks:new Map(),completedEncounters:new Set(),completedRegionalEvents:new Set(),knownKnowledgeNodeIds:r.ctx.knownKnowledgeNodeIds,elapsedGameMinutes:10,worldSeed:123}));
  r.choose(relay.targetDialogueId,followup);r.choose(relay.targetDialogueId,followup);
  expect(JSON.stringify(captureSaveSnapshot({displayName:'复谈',now:()=>new Date('2026-01-01T00:00:00Z'),mapResourceId:'map.round-01-grid',playerCol:1,playerRow:1,character:r.ctx.character!,inventory:r.ctx.inventory!,journal:r.ctx.journal,social:r.ctx.social,shopStocks:new Map(),completedEncounters:new Set(),completedRegionalEvents:new Set(),knownKnowledgeNodeIds:r.ctx.knownKnowledgeNodeIds,elapsedGameMinutes:10,worldSeed:123}))).toBe(beforeRepeat);
  const snapshot=captureSaveSnapshot({displayName:'人物测试',mapResourceId:'map.round-01-grid',playerCol:1,playerRow:1,character:r.ctx.character!,inventory:r.ctx.inventory!,journal:r.ctx.journal,social:r.ctx.social,shopStocks:new Map(),completedEncounters:new Set(),completedRegionalEvents:new Set(),knownKnowledgeNodeIds:r.ctx.knownKnowledgeNodeIds,elapsedGameMinutes:10,worldSeed:123,activeCompanionId:r.companion.id});
  const parsed=parseSaveSnapshot(JSON.parse(JSON.stringify(snapshot)));expect(parsed.ok).toBe(true);if(!parsed.ok)throw Error(parsed.message);
  const plan=planSnapshotRestore(parsed.snapshot,{profileIds:new Set([r.profile.id]),profileRecords:new Map([[r.profile.id,r.profile]]),mapResourceId:'map.round-01-grid',isWalkableCell:()=>true,isCellOccupied:()=>false,itemIds:new Set(r.ctx.items.keys()),itemRecords:r.ctx.items,martialArtIds:new Set(r.ctx.martialArts.keys()),questIds:new Set(r.ctx.quests.keys()),questObjectiveIds:new Map([...r.ctx.quests].map(([id,q])=>[id,new Set(q.objectives.map(o=>o.id))])),questRecords:r.ctx.quests,encounterIds:new Set(),shopIds:new Set(),npcIds:new Set(people.map(p=>p.npcId)),knowledgeNodeIds:new Set(r.ctx.knowledgeNodes.keys()),companionIds:new Set([r.companion.id])});expect(plan.ok).toBe(true);if(!plan.ok)throw Error(plan.errors.join());
  const restored=restoreRunState({snapshot:plan.snapshot,profile:r.profile,items:r.ctx.items,quests:r.ctx.quests,shops:new Map()});expect(npcKnows(restored.social,relay.targetNpcId,message)).toBe(true);expect(getRelationship(restored.social,relay.targetNpcId)).toBe(variant.delta);expect(restored.knownKnowledgeNodeIds.includes(delivered)).toBe(true);expect(restored.activeCompanionId).toBe(r.companion.id);const restoredContext={...r.ctx,social:restored.social,knownKnowledgeNodeIds:new Set(restored.knownKnowledgeNodeIds)};expect(getVisibleOptions(r.dialogues.get(relay.targetDialogueId)!.nodes.find(n=>n.id==='greet')!,restoredContext).filter(v=>v.option.nextNodeId?.startsWith('r136-'+relay.key+'-followup-')).map(v=>v.option.nextNodeId)).toEqual([followup]);
 });
 for(const rule of stanceRules)it(rule.id+' needs NPC memory and the correct current region',()=>{const r=fixture(),flag=rule.requiredSharedKnowledgeNodeIds[0]!;const resolve=(map:string)=>resolveCompanionStance(r.companion,{mapResourceId:map,sharedKnowledgeNodeIds:r.ctx.social.npcKnowledge.get(r.companion.npcId)??new Set()});r.ctx.knownKnowledgeNodeIds.add(flag);expect(resolve(rule.mapResourceIds![0]!).stanceId).toBeNull();const v=r.visible(people[0]!.dialogueId).find(v=>v.option.effects?.some(e=>e.kind==='shareKnowledgeNode'&&e.nodeId===flag))!;expect(v).toBeDefined();expect(applyDialogueEffects(v.option.effects!,r.ctx).ok).toBe(true);expect(applyDialogueEffects(v.option.effects!,r.ctx).ok).toBe(true);for(const map of rule.mapResourceIds!)expect(resolve(map).combatSupport).toEqual(rule.combatSupport);expect(resolve('map.unrelated').stanceId).toBeNull();expect(r.ctx.social.relationships.size).toBe(0);});
 it('isolates missing rule references, keeps default support and accepts legacy no-rules data',()=>{const r=fixture(),raw=structuredClone(r.companion);raw.stanceRules![0]!.requiredSharedKnowledgeNodeIds=['event.missing'];const maps=new Set(stanceRules.flatMap(s=>s.mapResourceIds??[]));const assembled=assembleCompanions({companions:[raw]},new Set([raw.npcId]),{knowledgeNodeIds:new Set(r.ctx.knowledgeNodes.keys()),mapResourceIds:maps});expect(assembled.warnings).toHaveLength(1);expect(assembled.companions.get(raw.id)!.stanceRules).toHaveLength(5);expect(assembled.companions.get(raw.id)!.combatSupport).toEqual(raw.combatSupport);delete raw.stanceRules;expect(parseCompanionSet({companions:[raw]}).ok).toBe(true);expect(resolveCompanionStance(raw,{mapResourceId:'any',sharedKnowledgeNodeIds:new Set()} ).stanceId).toBeNull();expect(assembleCompanions(null,new Set()).companions.size).toBe(0);});
 it('rejects duplicate and empty rule structure',()=>{const r=fixture(),raw=structuredClone(r.companion);raw.stanceRules!.push(raw.stanceRules![0]!);expect(parseCompanionSet({companions:[raw]}).ok).toBe(false);raw.stanceRules=[{...stanceRules[0]!,requiredSharedKnowledgeNodeIds:[]}];expect(parseCompanionSet({companions:[raw]}).ok).toBe(false);});
 it('refuses an unknown share atomically without recording a delivery or relation',()=>{const r=fixture(),relay=relays[0]!;r.ctx.speakerNpcId=relay.targetNpcId;const node=r.dialogues.get(relay.targetDialogueId)!.nodes.find(n=>n.id==='greet')!;const effects=node.options!.find(o=>o.nextNodeId==='r105-ledger-receive-0')!.effects!;expect(applyDialogueEffects(effects,r.ctx).ok).toBe(false);expect(r.ctx.social.npcKnowledge.size).toBe(0);expect(r.ctx.social.relationships.size).toBe(0);expect(r.ctx.knownKnowledgeNodeIds.size).toBe(0);});
 it('legacy v1 missing NPC memories never infers stance from player discoveries',()=>{const r=fixture();r.ctx.knownKnowledgeNodeIds.add('event.r100-record-guard');const snapshot=captureSaveSnapshot({displayName:'旧档',mapResourceId:'map.round-01-grid',playerCol:1,playerRow:1,character:r.ctx.character!,inventory:r.ctx.inventory!,journal:r.ctx.journal,social:r.ctx.social,shopStocks:new Map(),completedEncounters:new Set(),completedRegionalEvents:new Set(),knownKnowledgeNodeIds:r.ctx.knownKnowledgeNodeIds,elapsedGameMinutes:0,worldSeed:123});delete snapshot.social.npcKnowledge;Reflect.deleteProperty(snapshot,'activeCompanionId');const parsed=parseSaveSnapshot(JSON.parse(JSON.stringify(snapshot)));expect(parsed.ok).toBe(true);if(!parsed.ok)throw Error(parsed.message);const restored=restoreRunState({snapshot:parsed.snapshot,profile:r.profile,items:r.ctx.items,quests:r.ctx.quests,shops:new Map()});expect(restored.knownKnowledgeNodeIds).toContain('event.r100-record-guard');expect(restored.social.npcKnowledge.size).toBe(0);expect(restored.activeCompanionId).toBeNull();expect(resolveCompanionStance(r.companion,{mapResourceId:'map.round-01-grid',sharedKnowledgeNodeIds:restored.social.npcKnowledge.get(r.companion.npcId)??new Set()}).stanceId).toBeNull();});

});
