import { describe,it,expect } from 'vitest';
import { readFileSync } from 'node:fs';
import Ajv from 'ajv';
import { parseKnowledgeNodeSet,assembleKnowledgeGraph,projectKnowledgeProgress,type KnowledgeNodeData } from '../src/engine/knowledge-graph';
import { knowledgeNodes } from '../scripts/lib/round105-people-content.mjs';
const message:KnowledgeNodeData={id:'event.message',kind:'event',title:'旧口述标题',summary:'资料',knownByDefault:false,progress:{completedByNodeId:'event.done',pendingLabel:'待说明',completedLabel:'已说明'}};
const done:KnowledgeNodeData={id:'event.done',kind:'event',title:'说明回执',summary:'资料',knownByDefault:false};
describe('Round134 player knowledge progress',()=>{
 it('separates unreceived, pending and completed without editing discoveries',()=>{for(const [ids,state,label] of [[[],'unreceived','你尚未取得此见闻'],[['event.message'],'pending','待说明'],[['event.message','event.done'],'completed','已说明'],[['event.done'],'completed','已说明']] as const){const known=new Set<string>(ids);const before=[...known];expect(projectKnowledgeProgress(message,known)).toEqual({state,label});expect([...known]).toEqual(before);}});
 it('legacy nodes have no derived status',()=>{const {progress:_,...legacy}=message;expect(projectKnowledgeProgress(legacy,new Set(['event.done']))).toBeUndefined();expect(parseKnowledgeNodeSet({nodes:[legacy]})).toMatchObject({ok:true,warnings:[]});});
 it('malformed progress isolates metadata and preserves its node',()=>{for(const progress of [null,{}, {...message.progress,extra:1},{...message.progress,pendingLabel:''}]){const p=parseKnowledgeNodeSet({nodes:[{...message,progress},done]});expect(p.ok).toBe(true);if(!p.ok)throw Error();expect(p.data.nodes).toHaveLength(2);expect(p.data.nodes[0]!.progress).toBeUndefined();expect(p.warnings).toHaveLength(1);}});
 it('assembly drops missing and self references without mutating input',()=>{for(const completedByNodeId of ['event.missing','event.message']){const input={...message,progress:{...message.progress!,completedByNodeId}};const graph=assembleKnowledgeGraph({nodes:[input,done]},{edges:[]});expect(graph.nodes.size).toBe(2);expect(graph.nodes.get(input.id)!.progress).toBeUndefined();expect(graph.warnings).toHaveLength(1);expect(input.progress.completedByNodeId).toBe(completedByNodeId);}});
 it('valid reference retains authored labels and old graph size',()=>{const graph=assembleKnowledgeGraph({nodes:[message,done]},{edges:[]});expect(graph.warnings).toEqual([]);expect(graph.nodes.get(message.id)!.progress).toEqual(message.progress);});
 it('static schema accepts legacy and metadata but rejects malformed/extra fields',()=>{const schema=JSON.parse(readFileSync('data/schema/knowledge-nodes.schema.json','utf8'));const validate=new Ajv().compile(schema);expect(validate({nodes:[message,done]})).toBe(true);const {progress:_,...legacy}=message;expect(validate({nodes:[legacy]})).toBe(true);expect(validate({nodes:[{...message,progress:{...message.progress,extra:1}}]})).toBe(false);});
 it('three relay metadata rows match the author source and existing completion ids',()=>{const raw=JSON.parse(readFileSync('data/base/knowledge_graph/nodes.json','utf8'));const parsed=parseKnowledgeNodeSet(raw);expect(parsed.ok).toBe(true);if(!parsed.ok)throw Error();const graph=assembleKnowledgeGraph(parsed.data,{edges:[]});expect(graph.warnings).toEqual([]);expect(parsed.data.nodes.filter(n=>n.progress)).toHaveLength(3);for(const n of knowledgeNodes.filter(n=>n.progress)){expect(graph.nodes.get(n.id)!.progress).toEqual(n.progress);expect(graph.nodes.has(n.progress!.completedByNodeId)).toBe(true);}});
});
