import {readFileSync} from 'node:fs';
import {describe,it,expect,vi} from 'vitest';
import type Phaser from 'phaser';
vi.mock('phaser',()=>({default:{Input:{Keyboard:{KeyCodes:{UP:1,W:2,DOWN:3,S:4,ENTER:5,ESC:6,PAGE_UP:7,PAGE_DOWN:8}}}}}));
vi.mock('../src/game/ui-theme',()=>({UI_FONT_FAMILY:'monospace',addPixelPanelChrome:()=>{},addPixelSelection:()=>{}}));
vi.mock('../src/game/settings',()=>({uiFontSize:(n:number)=>`${n}px`}));
import {buildCombatResultSummary} from '../src/game/combat-result-summary';
import {BattlePanel} from '../src/game/combat-ui';
import {CombatSession,parseBattleEncounterSet} from '../src/engine/turn-based-combat';
import {createCharacterState,parseCharacterProfileSet,parseMartialArtSet} from '../src/engine/character-progression';
const read=(p:string)=>JSON.parse(readFileSync(new URL('../'+p,import.meta.url),'utf8'));
function setup(legacy=false){const pp=parseCharacterProfileSet(read('data/base/characters/round-04-profiles.json')),ap=parseMartialArtSet(read('data/base/skills/round-04-martial-arts.json')),bp=parseBattleEncounterSet(read('data/base/battles/round-05-encounters.json'));if(!pp.ok||!ap.ok||!bp.ok)throw Error('base');const profile=pp.set.profiles[0]!,player=createCharacterState(profile),encounter=structuredClone(bp.set.encounters[0]!);if(legacy)delete encounter.enemy.behavior;const session=new CombatSession({encounter,profile,player,martialArts:new Map(ap.set.martialArts.map(a=>[a.id,a]))});const keys=new Map<number,Set<()=>void>>(),shown:{text:string;destroyed:boolean}[]=[],container={setVisible(){return this},setDepth(){return this},add(){return this},removeAll(){for(const t of shown)t.destroyed=true;return this},destroy(){}};const scene={scale:{width:960,height:540},input:{keyboard:{addKey(code:number){if(!keys.has(code))keys.set(code,new Set());return {on(_e:string,fn:()=>void){keys.get(code)!.add(fn)},off(_e:string,fn:()=>void){keys.get(code)!.delete(fn)}};}}},add:{container:()=>container,rectangle:()=>({setStrokeStyle(){return this}}),text:(_x:number,_y:number,text:string)=>{const t={text,destroyed:false,height:21,width:0,setText(value:string){this.text=value;this.width=value.length*13;return this},setLineSpacing(){return this},setOrigin(){return this},setPosition(){return this},destroy(){this.destroyed=true}};shown.push(t);return t;}}} as unknown as Phaser.Scene;let closed=0;const panel=new BattlePanel(scene,{onClose:()=>closed++});panel.open(session);return {panel,session,player,visible:()=>shown.filter(t=>!t.destroyed).map(t=>t.text),closed:()=>closed,press:(code:number)=>{for(const fn of [...keys.get(code)??[]])fn();}};}
describe('Round124 real turn and recovery presentation',()=>{
 it('zero-qi waiting advances enemy cycle without free healing, qi or damage to enemy',()=>{const r=setup();r.player.qi.current=0;const intent=r.session.enemyIntent,hp=r.player.health.current,enemy=r.session.enemyView.health.current;r.session.playerWait();expect(r.player.qi.current).toBe(0);expect(r.player.health.current).toBeLessThan(hp);expect(r.session.enemyIntent).not.toBe(intent);expect(r.session.enemyView.health.current).toBe(enemy);expect(r.session.log.some(t=>t.text.includes('暂缓出招'))).toBe(true);});
 it('waiting can actually lose and restores authored ratios with no experience',()=>{const r=setup();r.player.qi.current=0;const xp=r.player.experience;for(let i=0;i<100&&!r.session.isOver;i++)r.session.playerWait();expect(r.session.finalResult).toEqual({outcome:'defeat',experienceGained:0,levelsGained:0});expect(r.player.health.current).toBe(Math.ceil(r.player.health.max*.6));expect(r.player.qi.current).toBe(Math.ceil(r.player.qi.max*.6));expect(r.player.experience).toBe(xp);const before=JSON.stringify(r.player),log=r.session.log.length;expect(r.session.playerWait()).toEqual({ok:false,reason:'not-player-turn'});expect(JSON.stringify(r.player)).toBe(before);expect(r.session.log).toHaveLength(log);});
 it('keyboard wait is independently selectable before retreat and can be used without qi',()=>{const r=setup();r.player.qi.current=0;for(let i=0;i<r.session.playerActions.length;i++)r.press(3);expect(r.visible().some(t=>t.includes('▸ 暂缓出招'))).toBe(true);r.press(5);expect(r.session.finalResult).toBeNull();expect(r.visible().some(t=>t.includes('暂缓出招，未回复'))).toBe(true);});
 it('keyboard retreat remains the last separate action',()=>{const r=setup();r.press(1);r.press(5);expect(r.session.finalResult?.outcome).toBe('fled');expect(r.visible().join('')).toContain('战斗结果：撤退');});
 it('result summary states actual restored health and qi, not full refill',()=>{const r=setup();while(!r.session.isOver)r.session.playerWait();const summary=buildCombatResultSummary(r.session);expect(summary).toContain('战败恢复已生效');expect(summary).toContain('生命 '+r.player.health.current+'/'+r.player.health.max);expect(summary).toContain('内力 '+r.player.qi.current+'/'+r.player.qi.max);expect(summary).toContain('本场经验 +0');expect(summary).toContain('差事后果在离开战场时结算');});
 it('long authored result pages survive forward/back reading before one close',()=>{const r=setup();r.press(6);const source=r.session.log.find(t=>t.kind==='fled')!;source.text='渡'.repeat(1800);r.press(7);expect(r.closed()).toBe(0);const seen:string[]=[];for(let i=0;i<200&&r.closed()===0;i++){seen.push(r.visible().join(''));r.press(5);}expect(r.closed()).toBe(1);expect(seen.join('').match(/渡/g)?.length).toBeGreaterThanOrEqual(1800);r.press(5);expect(r.closed()).toBe(1);});
});
