import {readFileSync,writeFileSync,mkdtempSync,mkdirSync,cpSync,rmSync} from 'node:fs';
import {resolve,join,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {beforeAll,afterAll,describe,it,expect,vi} from 'vitest';
import Ajv from 'ajv';
import {loadWorldData,type LoadedWorld} from '../src/game/world-loader';
import {parseWorldMap,assembleWorldMap} from '../src/engine/world-map';
import {buildRegionalGuideEntries,resolveRegionalGuideDestination,REGION_GUIDE_PREFIX,type RegionalGuideInput} from '../src/engine/regional-guide';
import {createShopStockRuntime} from '../src/engine/item-system';
import {resolveCellNavigationGuide,arrivalActionHint} from '../src/engine/world-navigation-guidance';
import {createQuestJournal} from '../src/engine/quest-system';
import {resolveQuestNavigationTarget} from '../src/engine/quest-navigation';
import {transitionAccessReason} from '../src/engine/transition-access';
import {findWorldTravelRoute} from '../src/engine/world-travel';
const root=fileURLToPath(new URL('../',import.meta.url));const read=(path:string)=>JSON.parse(readFileSync(join(root,path),'utf8'));
let world:LoadedWorld;
beforeAll(async()=>{vi.spyOn(console,'info').mockImplementation(()=>{});vi.spyOn(console,'warn').mockImplementation(()=>{});vi.stubGlobal('fetch',async(input:RequestInfo|URL)=>{const url=typeof input==='string'?input:input instanceof URL?input.href:input.url;try{return new Response(readFileSync(join(root,'data',decodeURIComponent(new URL(url,'http://r106.test').pathname)), 'utf8'),{status:200,headers:{'content-type':'application/json'}});}catch{return new Response('not found',{status:404});}});const loaded=await loadWorldData();if(!loaded.ok)throw Error(loaded.lines.join('\n'));world=loaded.world;
 if(process.env.WUXIA_R106_REPORT==='1'){
  const maps=['map.round-01-grid','map.round-10-mist-ferry','map.round-74-cloud-ridge','map.round-82-east-coast','map.round-92-north-pass','map.round-97-lanxin-isle'];
  const report=maps.map(map=>{const i=input(map),grid=world.maps.get(map)!,blockers=new Set([...(i.periodNpcs??i.baseNpcs).filter(n=>n.record.mapResourceId===map).map(n=>n.col+','+n.row),...world.assembly.encounters.filter(e=>e.record.mapResourceId===map).map(e=>e.col+','+e.row)]);
   const rows=buildRegionalGuideEntries(i).filter(e=>(e.category==='supply'||e.category==='exit')&&e.destinationId!==null).map(e=>{const target=resolveRegionalGuideDestination(i,e.destinationId!)!,route=findWorldTravelRoute(world.worldMap,map,target.mapResourceId),guide=resolveCellNavigationGuide(world.worldMap,map,target,grid,grid.data.playerStart,blockers);return {category:e.category,title:e.title,destinationMapResourceId:target.mapResourceId,transitionCount:route?.legs.length??null,firstLocalSegmentCells:'path'in guide?guide.path.length-1:null,status:guide.status,detail:e.detail};});
   return {mapResourceId:map,name:world.worldMap.regions.find(r=>r.mapResourceId===map)!.name,role:world.worldMap.regionGuides!.find(g=>g.mapResourceId===map)!.role,start:grid.data.playerStart,rows};});
  writeFileSync(join(root,'iterations/round-106/region-route-facts.json'),JSON.stringify({scope:'Six authored playerStart positions, morning NPC and all assembled battle blockers; static first local segments. Not a real journey, not minutes and not longest no-decision road.',regions:report},null,2)+'\n');
 }
});
afterAll(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();});
function input(map='map.round-01-grid'):RegionalGuideInput{return {worldMap:world.worldMap,currentMapResourceId:map,baseNpcs:world.assembly.npcs,periodNpcs:world.assembly.npcsByPeriod.get('period.morning'),shops:world.assembly.shops,items:world.assembly.items,shopStocks:new Map([...world.assembly.shops].map(([id,shop])=>[id,createShopStockRuntime(shop)])),knownKnowledgeNodeIds:new Set()};}
describe('Round106 default regional roles and actual live navigation facts',()=>{
 it('loads all 22 roles without warnings or changed resources',()=>{expect(world.optionalWarnings).toEqual([]);expect(world.worldMap.regionGuides).toHaveLength(22);expect(new Set(world.worldMap.regionGuides!.map(g=>g.mapResourceId))).toEqual(new Set(world.worldMap.regions.map(r=>r.mapResourceId)));expect(world.assembly.quests.size).toBe(65);});
 for(const [map,local]of [['map.round-01-grid',true],['map.round-10-mist-ferry',false],['map.round-74-cloud-ridge',true],['map.round-82-east-coast',true],['map.round-92-north-pass',false],['map.round-97-lanxin-isle',false]] as const)it(map+' exposes real supplies, exits and navigable destinations',()=>{const i=input(map),entries=buildRegionalGuideEntries(i),supply=entries.filter(e=>e.category==='supply');expect(supply.length).toBeGreaterThan(0);expect(supply.every(e=>e.detail.includes(' · 本地 · '))).toBe(local);for(const entry of supply){const target=resolveRegionalGuideDestination(i,entry.destinationId!)!;expect(target).not.toBeNull();expect(target.arrivalAction).toBe('shop');const route=findWorldTravelRoute(world.worldMap,map,target.mapResourceId)!;expect(route).not.toBeNull();const result=resolveCellNavigationGuide(world.worldMap,map,target,world.maps.get(map)!,world.maps.get(map)!.data.playerStart);expect(['en-route','at-gate','arrived']).toContain(result.status);}
  const gates=world.worldMap.transitions.filter(g=>g.from.mapResourceId===map);expect(entries.filter(e=>e.category==='exit')).toHaveLength(gates.length);for(const gate of gates){const target=resolveRegionalGuideDestination(i,REGION_GUIDE_PREFIX+'gate:'+gate.id)!;if(transitionAccessReason(gate,i.knownKnowledgeNodeIds)!==null){expect(target).toBeNull();expect(entries.find(e=>e.id==='exit:'+gate.id)!.detail).toContain('尚未开通');continue;}expect(target).toMatchObject({...gate.from,arrivalAction:'travel',approachRadius:1});expect(arrivalActionHint(target.arrivalAction!)).toContain('按 E');}
 });
 it('finite purchases/exhaustion and unlimited stock remain distinct, and the guide is read-only',()=>{const i=input(),stock=i.shopStocks.get('shop.jiang-baiwei-peddler-cart')??[...i.shopStocks.values()][0]!;const before=JSON.stringify([...i.shopStocks].map(([id,s])=>[id,[...s]]));buildRegionalGuideEntries(i);expect(JSON.stringify([...i.shopStocks].map(([id,s])=>[id,[...s]]))).toBe(before);stock.set('item.qingxin-wan',4);let entry=buildRegionalGuideEntries(i).find(e=>e.category==='supply')!;expect(entry.detail).toContain('清心丸 12两余4');expect(entry.detail).toContain('回春膏 15两常备');stock.set('item.qingxin-wan',0);entry=buildRegionalGuideEntries(i).find(e=>e.category==='supply')!;expect(entry.detail).not.toContain('清心丸');});
 it('does not offer unusable shelves, missing keepers or material-only stores',()=>{const i=input();const shops=new Map(i.shops);for(const [id,shop]of shops)shops.set(id,{...shop,stock:shop.stock.filter(s=>!i.items.get(s.itemId)?.consumable)});expect(buildRegionalGuideEntries({...i,shops}).filter(e=>e.category==='supply')).toEqual([]);expect(buildRegionalGuideEntries({...i,baseNpcs:[],periodNpcs:[]}).filter(e=>e.category==='supply')).toEqual([]);});
 it('finds nearest directed reachable backup when the local medicine shelf is exhausted',()=>{const i=input();for(const stock of i.shopStocks.values())for(const id of stock.keys())stock.set(id,0);expect(buildRegionalGuideEntries(i).filter(e=>e.category==='supply')).toHaveLength(0);const remote=[...i.shops].find(([_id,s])=>s.record.npcId==='char.r83-jin-yunfan')!;expect(remote).toBeDefined();(i.shopStocks as Map<string,Map<string,number>>).set(remote[0],createShopStockRuntime(remote[1]));const offers=buildRegionalGuideEntries(i).filter(e=>e.category==='supply');expect(offers).toHaveLength(1);expect(offers[0]!.title).toBe(remote[1].record.name);expect(offers[0]!.detail).toContain('跨');});
 it('live placement wins over scheduled/base coordinates and follower never returns to its old home',()=>{const i=input('map.round-97-lanxin-isle'),npc=i.baseNpcs.find(n=>n.record.id==='char.r97-ji-wuchao')!;const moved={...npc,col:33,row:44};expect(resolveRegionalGuideDestination({...i,currentMapNpcs:[moved]},REGION_GUIDE_PREFIX+'npc:'+npc.record.id)).toMatchObject({col:33,row:44});const gu=i.baseNpcs.find(n=>n.record.id==='char.gu-yechen')!;const follow={...i,activeFollowerNpcId:gu.record.id,follower:{npc:gu,col:52,row:52,mapResourceId:i.currentMapResourceId}};expect(resolveRegionalGuideDestination(follow,REGION_GUIDE_PREFIX+'npc:'+gu.record.id)).toMatchObject({mapResourceId:i.currentMapResourceId,col:52,row:52});expect(buildRegionalGuideEntries(follow).find(e=>e.id==='people:'+gu.record.id)!.detail).toContain('真实同行');expect(resolveRegionalGuideDestination({...i,activeFollowerNpcId:gu.record.id},REGION_GUIDE_PREFIX+'npc:'+gu.record.id)).toBeNull();});
 it('same stable NPC selector follows actual scheduled positions across periods',()=>{const i=input('map.round-97-lanxin-isle'),id='char.r97-ji-wuchao',selector=REGION_GUIDE_PREFIX+'npc:'+id;const morning=resolveRegionalGuideDestination(i,selector),night=resolveRegionalGuideDestination({...i,periodNpcs:world.assembly.npcsByPeriod.get('period.night')},selector);expect(morning).not.toBeNull();expect(night).not.toBeNull();expect([morning!.col,morning!.row]).not.toEqual([night!.col,night!.row]);});
 it('only reveals already public/discovered landmarks',()=>{const i=input('map.round-97-lanxin-isle'),hidden=i.worldMap.landmarks.find(l=>l.mapResourceId===i.currentMapResourceId&&l.discoveryNodeId)!;expect(hidden).toBeDefined();expect(buildRegionalGuideEntries(i).some(e=>e.id==='landmark:'+hidden.id)).toBe(false);const known=new Set([hidden.discoveryNodeId!]);expect(buildRegionalGuideEntries({...i,knownKnowledgeNodeIds:known}).some(e=>e.id==='landmark:'+hidden.id)).toBe(true);});
 it('keeps blocked destinations for future re-resolution and reports missing selectors',()=>{const i=input(),npc=i.baseNpcs.find(n=>n.record.id==='char.jiang-baiwei')!,target=resolveRegionalGuideDestination(i,REGION_GUIDE_PREFIX+'npc:'+npc.record.id)!;const blocked=new Set([`${target.col+1},${target.row}`,`${target.col-1},${target.row}`,`${target.col},${target.row+1}`,`${target.col},${target.row-1}`]);const result=resolveCellNavigationGuide(world.worldMap,i.currentMapResourceId,target,world.maps.get(i.currentMapResourceId)!,{col:43,row:37},blocked);expect(result.status).toBe('route-blocked');expect(resolveCellNavigationGuide(world.worldMap,i.currentMapResourceId,target,world.maps.get(i.currentMapResourceId)!,{col:43,row:37}).status).toBe('en-route');expect(resolveRegionalGuideDestination(i,REGION_GUIDE_PREFIX+'npc:missing')).toBeNull();expect(resolveRegionalGuideDestination(i,REGION_GUIDE_PREFIX+'gate:missing')).toBeNull();expect(resolveRegionalGuideDestination(i,'invalid')).toBeNull();});
 it('legacy no-guides data stays valid and invalid role structure is rejected',()=>{const raw=read('data/base/world/world-map.json'),validate=new Ajv().compile(read('data/schema/world-map.schema.json'));delete raw.regionGuides;expect(validate(raw)).toBe(true);expect(parseWorldMap(raw).ok).toBe(true);raw.regionGuides=[{mapResourceId:'map.round-01-grid',role:'made-up',advice:'test'}];expect(validate(raw)).toBe(false);expect(parseWorldMap(raw).ok).toBe(false);});
 it('bad or repeated guide map references isolate the guide without removing the world',()=>{const raw=read('data/base/world/world-map.json');raw.regionGuides.push({...raw.regionGuides[0],mapResourceId:'map.missing'},raw.regionGuides[0]);const parsed=parseWorldMap(raw);if(!parsed.ok)throw Error(parsed.errors.join());const assembled=assembleWorldMap(parsed.data,world.maps);if('ok'in assembled)throw Error(assembled.errors.join());expect(assembled.regionGuides).toHaveLength(22);expect(assembled.warnings.filter(w=>w.includes('区域指南'))).toHaveLength(2);expect(assembled.regions).toHaveLength(22);});
 it('quest navigation to a real follower uses its current region and P then T, never its old home',()=>{const i=input('map.round-97-lanxin-isle'),gu=i.baseNpcs.find(n=>n.record.id==='char.gu-yechen')!,q=structuredClone([...world.assembly.quests.values()][0]!);q.objectives=[{id:'objective.fixture-talk',kind:'talkToNpc',targetId:gu.record.id,requiredCount:1,text:'fixture'}];const quests=new Map([[q.id,q]]),journal=createQuestJournal(quests);journal.states.get(q.id)!.status='active';const follower={...gu,col:52,row:52,record:{...gu.record,mapResourceId:i.currentMapResourceId}};const result=resolveQuestNavigationTarget({quests,journal,questId:q.id,worldMap:world.worldMap,baseNpcs:i.baseNpcs,periodNpcs:i.periodNpcs??i.baseNpcs,currentFollower:follower,encounters:world.assembly.encounters,knowledgeNodeTitles:new Map(),shops:i.shops,shopStocks:i.shopStocks,currentMapResourceId:i.currentMapResourceId});expect(result.status).toBe('target');if(result.status==='target'){expect(result.target).toMatchObject({mapResourceId:i.currentMapResourceId,col:52,row:52,arrivalAction:'companion'});expect(arrivalActionHint(result.target.arrivalAction)).toContain('按 P 再 T');}});
 it('role source repeats byte-stably in a checked temporary sandbox',()=>{const dir=resolve(mkdtempSync(join(tmpdir(),'wuxia-r106-')));try{mkdirSync(join(dir,'scripts','lib'),{recursive:true});mkdirSync(join(dir,'data','base','world'),{recursive:true});for(const p of ['scripts/deepen-round106-regions.mjs','scripts/lib/round106-region-content.mjs','data/base/world/world-map.json'])cpSync(join(root,p),join(dir,p));const run=()=>execFileSync(process.execPath,[join(dir,'scripts','deepen-round106-regions.mjs')]);run();const before=readFileSync(join(dir,'data/base/world/world-map.json'),'utf8');run();expect(readFileSync(join(dir,'data/base/world/world-map.json'),'utf8')).toBe(before);expect(before).toBe(readFileSync(join(root,'data/base/world/world-map.json'),'utf8'));}finally{if(!dir.startsWith(resolve(tmpdir())+sep+'wuxia-r106-'))throw Error('unsafe sandbox');rmSync(dir,{recursive:true,force:true});}});
});
