import {readFileSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {CombatSession,parseBattleEncounterSet} from '../src/engine/turn-based-combat';
import {createCharacterState,parseCharacterProfileSet,parseMartialArtSet} from '../src/engine/character-progression';
import {companionCadenceLabel} from '../src/game/companion-cadence';
const read=(p:string)=>JSON.parse(readFileSync('data/base/'+p,'utf8'));
function setup(companion=true,kind:'attack'|'heal'='attack',everyPlayerActions=2){const pp=parseCharacterProfileSet(read('characters/round-04-profiles.json')),ap=parseMartialArtSet(read('skills/round-04-martial-arts.json')),bp=parseBattleEncounterSet(read('battles/round-05-encounters.json'));if(!pp.ok||!ap.ok||!bp.ok)throw Error('base');const profile=pp.set.profiles[0]!,player=createCharacterState(profile),encounter=structuredClone(bp.set.encounters.find(e=>e.id==='encounter.r142-patrol-drill')!);player.health.current=player.health.max;return {player,encounter,profile,martialArts:new Map(ap.set.martialArts.map(a=>[a.id,a])),session:new CombatSession({encounter,profile,player,martialArts:new Map(ap.set.martialArts.map(a=>[a.id,a])),...(companion?{companion:{name:'同行测试人',support:{kind,power:9,everyPlayerActions}}}:{})})};}
describe('Round142 companion cadence and patrol drill',()=>{
 it('projects 2→1→2 and keeps the exact attack receipt',()=>{const r=setup();expect(r.session.companionCadence).toMatchObject({successfulActions:0,actionsUntilSupport:2});expect(companionCadenceLabel(r.session.companionCadence)).toContain('攻击至多9');r.session.playerUse('missing');expect(r.session.companionCadence?.actionsUntilSupport).toBe(2);r.session.playerWait();expect(r.session.companionCadence?.actionsUntilSupport).toBe(1);const before=r.session.enemyView.health.current;r.session.playerWait();expect(r.session.companionCadence).toMatchObject({successfulActions:2,actionsUntilSupport:2});expect(r.session.log.find(e=>e.companionSupport)!.companionSupport).toMatchObject({actualAmount:9,before,after:before-9,actionNumber:2});});
 it('projection is a copy and cannot mutate combat cadence',()=>{const r=setup(),view=r.session.companionCadence!;view.actionsUntilSupport=99;view.power=99;expect(r.session.companionCadence).toMatchObject({actionsUntilSupport:2,power:9});expect(r.session.log).toHaveLength(1);});
 it('every-four and healing wording use authored values',()=>{const r=setup(true,'heal',4);r.session.playerWait();expect(r.session.companionCadence?.actionsUntilSupport).toBe(3);expect(companionCadenceLabel(r.session.companionCadence)).toContain('恢复至多9');});
 it('unaffordable skills do not advance support',()=>{const r=setup();r.player.qi.current=0;const costly=r.session.playerActions.find(a=>a.art.combat.qiCost>0);expect(costly).toBeDefined();expect(r.session.playerUse(costly!.art.id).ok).toBe(false);expect(r.session.companionCadence?.successfulActions).toBe(0);});
 it('no companion or closed battle has no projected support',()=>{expect(setup(false).session.companionCadence).toBeNull();expect(companionCadenceLabel(null)).toBeNull();const r=setup();r.session.flee();expect(r.session.companionCadence).toBeNull();expect(r.session.playerWait().ok).toBe(false);expect(setup().session.companionCadence?.successfulActions).toBe(0);});
 it('repeatable practice has no encounter experience; existing encounters are preserved',()=>{const r=setup();expect(r.encounter.repeatable).toBe(true);expect(r.encounter.victoryExperience).toBe(0);expect(read('battles/round-05-encounters.json').encounters.some((e:{id:string})=>e.id==='encounter.r101-beacon-raider')).toBe(true);});
 it('immediate victory ends cadence before support and awards zero practice experience',()=>{const r=setup();r.encounter.enemy.health=1;const s=new CombatSession({encounter:r.encounter,profile:r.profile,player:r.player,martialArts:r.martialArts,companion:{name:'test',support:{kind:'attack',power:9,everyPlayerActions:1}}});s.playerUse('skill.jianghu-sanshou');expect(s.companionCadence).toBeNull();expect(s.finalResult).toMatchObject({outcome:'victory',experienceGained:0});expect(s.log.filter(e=>e.companionSupport)).toHaveLength(0);});
});
