import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {describe,it,expect} from 'vitest';
import {regionEventConditionsMet,selectInteractableRegionEvent} from '../src/engine/world-map';
import {parseDialogueSet} from '../src/engine/dialogue-graph';
const read=(p:string)=>JSON.parse(readFileSync('data/base/'+p,'utf8'));
const raw=read('dialogues/round-83-east-coast-conversations.json');
const talk=raw.conversations.find((d:{id:string})=>d.id==='dlg.r83-gu-chaosheng-tide-line');
const guide=talk.nodes.find((n:{id:string})=>n.id==='channel-accepted');
describe('Round170 useful daytime sea route',()=>{
 it('offers a real gate and named investigations without auto completion',()=>{expect(parseDialogueSet(raw).ok).toBe(true);for(const text of ['(91,71)','阮回澜','谢照汀','潮生屿','傍晚再回青帆','不会自动让暮潮调查完成'])expect(guide.text).toContain(text);const world=read('world/world-map.json');const gate=world.transitions.find((g:{id:string})=>g.id==='gate.r84-east-coast-to-windward-isle');expect(gate.from).toEqual({mapResourceId:'map.round-82-east-coast',col:91,row:71});expect(gate.to.mapResourceId).toBe('map.round-84-windward-isle');expect(guide.effects).toBeUndefined();});
 it('retains night and net knowledge requirements',()=>{const world=read('world/world-map.json');const event=world.events.find((e:{id:string})=>e.id==='event.r83-night-channel');expect(event.conditions).toEqual({knowledgeNodeIds:['place.r83-net-shoals'],periodIds:['period.dusk','period.night']});expect(event.col).toBe(63);expect(event.row).toBe(72);const quest=read('quests/round-83-east-coast-quests.json').quests.find((q:{id:string})=>q.id==='quest.r83-night-channel');expect(quest.prerequisiteQuestIds).toEqual(['quest.r83-net-recovery']);expect(quest.rewards).toEqual({experience:36,currency:30});});
 it('accepted quests retain a free repeat guide without accepting twice',()=>{const entry=talk.nodes[0].options.find((o:{text:string})=>o.text==='白日可先去哪调查，暮潮怎样回访？');expect(entry.conditions).toEqual([{kind:'questStatus',questId:'quest.r83-night-channel',status:'active'}]);expect(entry.nextNodeId).toBe('channel-accepted');expect(entry.effects).toBeUndefined();});
 it('actual evaluator refuses daylight and missing knowledge, accepts dusk from correct side',()=>{const event=read('world/world-map.json').events.find((e:{id:string})=>e.id==='event.r83-night-channel');const ctx={knownKnowledgeNodeIds:new Set(['place.r83-net-shoals']),periodId:'period.morning',weatherId:null};expect(regionEventConditionsMet(event,ctx)).toBe(false);expect(regionEventConditionsMet(event,{...ctx,periodId:'period.dusk',knownKnowledgeNodeIds:new Set()})).toBe(false);const dusk={...ctx,periodId:'period.dusk'};expect(regionEventConditionsMet(event,dusk)).toBe(true);expect(selectInteractableRegionEvent([event],{mapResourceId:event.mapResourceId,col:63,row:71},new Set(),dusk)?.event.id).toBe(event.id);expect(selectInteractableRegionEvent([event],{mapResourceId:event.mapResourceId,col:62,row:72},new Set(),dusk)).toBeNull();});
 it('author replay retains current complete dialogue data',()=>{const out=execFileSync(process.execPath,['--input-type=module','-e',"import {readFileSync} from 'node:fs';import {deepenSeaDialogues} from './scripts/lib/round102-sea-content.mjs';const d=JSON.parse(readFileSync('data/base/dialogues/round-83-east-coast-conversations.json','utf8'));deepenSeaDialogues(d);console.log(JSON.stringify(d));"],{encoding:'utf8'});expect(JSON.parse(out)).toEqual(raw);});
});
