import {describe,it,expect,vi} from 'vitest';
import type Phaser from 'phaser';
vi.mock('phaser',()=>({default:{Input:{Keyboard:{KeyCodes:{ESC:1,ENTER:2,LEFT:3,RIGHT:4,UP:5,DOWN:6,SPACE:7}}}}}));
vi.mock('../src/game/settings',()=>({uiFontSize:(n:number)=>`${Math.round(n*1.6)}px`}));
vi.mock('../src/game/ui-theme',()=>({addPixelPanelChrome:()=>{},UI_FONT_FAMILY:'monospace',UI_PALETTE:{accent:'#fff',muted:'#aaa',text:'#eee',jade:'#afa'}}));
import {RegionalGuidePanel} from '../src/game/regional-guide-ui';
describe('Round128 guide explicit line spacing',()=>{
 for(const [width,height]of [[960,540],[640,360]] as const)it('actual line heights remain inside reserved bands '+width,()=>{const texts:{text:string;y:number;height:number;dead:boolean;spacing:number}[]=[];const c={setDepth(){return this},setVisible(){return this},add(){return this},removeAll(){for(const t of texts)t.dead=true;return this},destroy(){}};const scene={scale:{width,height},input:{keyboard:{addKey(){return{on(){},off(){}}}}},add:{container:()=>c,text:(_x:number,y:number,text:string,style:{fontSize:string;lineSpacing:number})=>{const size=parseInt(style.fontSize,10);expect(style.lineSpacing).toBe(Math.ceil(size*0.4));const t={text,y,height:size,dead:false,spacing:style.lineSpacing,context:{measureText:(s:string)=>({width:Array.from(s).length*size})},setOrigin(){return this},setText(s:string){this.text=s;this.height=s.split('\n').length*size+Math.max(0,s.split('\n').length-1)*style.lineSpacing;return this},setPosition(_x:number,y:number){this.y=y;return this},setColor(){return this},destroy(){this.dead=true}};texts.push(t);return t;}}} as unknown as Phaser.Scene;const panel=new RegionalGuidePanel(scene,()=>{});panel.open({name:'江南道',role:'枢纽',advice:'先在镇中接口信，补药与问纸墨，书院可拜师；出镇前用活动差事导航核下一步。东行石阶渡口去雾雨渡口，善正后不必再跑沈府才领谢仪。',entries:[{id:'npc',category:'supply',title:'药担',detail:'当前位置(45,39)，可购买伤药。',destinationId:'npc'}],onNavigate:()=>{}});const shown=texts.filter(t=>!t.dead&&t.text.length);const advice=shown.find(t=>t.text.startsWith('先在镇中'));const cats=shown.find(t=>t.text.includes('◆'))!;if(advice)expect(advice.y+advice.height).toBeLessThanOrEqual(cats.y);for(const t of shown)expect(t.y+t.height).toBeLessThanOrEqual((height+Math.min(500,height-40))/2);panel.destroy();});
});
