import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,cpSync,rmSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {describe,it,expect} from 'vitest';
import {repairRound03Raw,repairRound30Raw} from '../scripts/lib/round128-aid-donation.mjs';
const read=(p:string)=>readFileSync(p,'utf8');
const raw03=read('data/base/dialogues/round-03-conversations.json'),raw30=read('data/base/dialogues/round-30-conversations.json');
function removeDirection(set:ReturnType<typeof JSON.parse>){for(const c of set.conversations){c.nodes=c.nodes.filter((n:{id:string})=>n.id!=='r128-west-wicket');for(const n of c.nodes)if(n.options)n.options=n.options.filter((o:{nextNodeId:string})=>o.nextNodeId!=='r128-west-wicket');}return set;}
function pristine03(){const d=removeDirection(JSON.parse(raw03)),c=d.conversations.find((c:{id:string})=>c.id==='dlg.ma-shangyi-notice-board'),board=c.nodes.find((n:{id:string})=>n.id==='board'),o=board.options.find((o:{nextNodeId:string})=>o.nextNodeId==='quest-delivered');board.text='有劳。做成做不成，都请回来告我一声。';o.text='回春膏备齐了，这就交给你带去。';o.effects=o.effects.filter((e:{kind:string})=>e.kind!=='adjustMorality');c.nodes.find((n:{id:string})=>n.id==='quest-delivered').text='（马尚义接过药，掂了掂分量）齐了！我这就给人送去。你这份心意，镇上的乡邻都记着——往后有什么难处，尽管来寻我。';return d;}
const safeRemove=(root:string)=>{if(!root.startsWith(resolve(tmpdir())+sep))throw Error('bad temp');rmSync(root,{recursive:true,force:true});};
describe('Round128 actual author generators',()=>{
 for(const eol of ['\n','\r\n'])it('pure repairs preserve input EOL and unrelated conversations, second replay zero difference '+JSON.stringify(eol),()=>{const old=pristine03(),source=JSON.stringify(old,null,2).split('\n').join(eol),next=repairRound03Raw(source);expect(JSON.parse(next)).toEqual(JSON.parse(raw03));expect(repairRound03Raw(next)).toBe(next);expect(eol==='\r\n'?next.replace(/\r\n/g,'').includes('\n'):next.includes('\r')).toBe(false);const other=JSON.parse(next).conversations.filter((c:{id:string})=>!['dlg.ma-shangyi-notice-board','dlg.ye-tingzhou-mentor'].includes(c.id));expect(other).toEqual(old.conversations.filter((c:{id:string})=>!['dlg.ma-shangyi-notice-board','dlg.ye-tingzhou-mentor'].includes(c.id)));const thirty=JSON.stringify(removeDirection(JSON.parse(raw30)),null,2).split('\n').join(eol);expect(JSON.parse(repairRound30Raw(thirty))).toEqual(JSON.parse(raw30));});
 it('incremental CLI resolves paths independently of cwd, replays byte-identically, preflights all data before writes',()=>{const root=mkdtempSync(join(tmpdir(),'wuxia-r128-'));try{mkdirSync(join(root,'scripts/lib'),{recursive:true});mkdirSync(join(root,'data/base/maps'),{recursive:true});mkdirSync(join(root,'data/base/dialogues'),{recursive:true});for(const f of ['apply-round128.mjs','lib/round128-town-wicket.mjs','lib/round128-aid-donation.mjs'])cpSync(resolve('scripts',f),join(root,'scripts',f));const m=JSON.parse(read('data/base/maps/round-01-grid.json'));m.grid[37]=m.grid[37].slice(0,42)+'#'+m.grid[37].slice(43);m.art.layers.find((l:{id:string})=>l.id==='layer-2').cells[37][42]=0;m.art.layers.find((l:{id:string})=>l.id==='layer-3').cells[37][42]=409;const mp=join(root,'data/base/maps/round-01-grid.json'),dp=join(root,'data/base/dialogues/round-03-conversations.json'),tp=join(root,'data/base/dialogues/round-30-conversations.json');const original=JSON.stringify(m,null,2)+'\n';writeFileSync(mp,original);writeFileSync(dp,JSON.stringify(pristine03(),null,2).replace(/\n/g,'\r\n'));writeFileSync(tp,'invalid');expect(()=>execFileSync(process.execPath,[join(root,'scripts/apply-round128.mjs')],{cwd:tmpdir(),stdio:'pipe'})).toThrow();expect(read(mp)).toBe(original);writeFileSync(tp,JSON.stringify(removeDirection(JSON.parse(raw30)),null,2));execFileSync(process.execPath,[join(root,'scripts/apply-round128.mjs')],{cwd:tmpdir()});const saved=[read(mp),read(dp),read(tp)];execFileSync(process.execPath,[join(root,'scripts/apply-round128.mjs')],{cwd:tmpdir()});expect([read(mp),read(dp),read(tp)]).toEqual(saved);}finally{safeRemove(root);}});
 it('R51 real importer repairs exactly the target road, adjacent409 remains blocked',()=>{const root=mkdtempSync(join(tmpdir(),'wuxia-r128-source-'));try{for(const dir of ['scripts/lib','scripts/sources','data/base/maps'])mkdirSync(join(root,dir),{recursive:true});for(const f of ['import-round51-kenney-world.mjs','lib/round128-town-wicket.mjs','sources/kenney-roguelike-sample-map.tmx'])cpSync(resolve('scripts',f),join(root,'scripts',f));execFileSync(process.execPath,[join(root,'scripts/import-round51-kenney-world.mjs')],{cwd:root});const m=JSON.parse(read(join(root,'data/base/maps/round-01-grid.json')));expect(m.grid[37][42]).toBe('.');expect(m.art.layers.find((l:{id:string})=>l.id==='layer-2').cells[37][42]).toBe(409);expect(m.grid[36][42]).toBe('#');expect(m.art.layers.find((l:{id:string})=>l.id==='layer-3').cells[36][42]).toBe(409);}finally{safeRemove(root);}});
});
