import {readFileSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {buildDialogueAftermathGuideEntries,type QuestGuideInput} from '../src/engine/quest-guide';
import type {DialogueData} from '../src/engine/dialogue-graph';
import type {DialogueRuntimeContext} from '../src/engine/dialogue-runtime';
import {createSocialState} from '../src/engine/social-state';
import {createFactionMembershipState} from '../src/engine/faction-system';
import type {PlacedNpc} from '../src/engine/npc-placement';
import type {WorldMapAssembly} from '../src/engine/world-map';
const context=():DialogueRuntimeContext=>({quests:new Map(),journal:{states:new Map(),trackedQuestId:null},items:new Map(),inventory:null,social:createSocialState(),speakerNpcId:'npc',knownKnowledgeNodeIds:new Set(),knowledgeNodes:new Map(),character:null,factions:new Map(),martialArts:new Map(),factionState:createFactionMembershipState(),timeOfDayPeriodId:'morning'});
function done(c:DialogueRuntimeContext,id='quest'){c.journal.states.set(id,{questId:id,status:'completed',objectiveCounts:new Map()});}
const graph=():DialogueData=>({id:'dlg',startNodeId:'start',nodes:[{id:'start',text:'入口',options:[{text:'核对记录',nextNodeId:'answer',conditions:[{kind:'knowledgeKnown',nodeId:'choice'}]}]},{id:'answer',text:'不可提前泄露的答案'}]});
const npc:PlacedNpc={record:{id:'npc',name:'测试人',mapResourceId:'map',position:{col:1,row:2},dialogueId:'dlg',shopId:null,questGiver:false,schedule:[]},col:1,row:2};
function input(g=graph(),c=context()):QuestGuideInput{return {guide:{worldMap:{} as WorldMapAssembly,currentMapResourceId:'map',baseNpcs:[npc],shops:new Map(),items:new Map(),shopStocks:new Map(),knownKnowledgeNodeIds:c.knownKnowledgeNodeIds},quests:new Map(),journal:c.journal,access:{},encounters:[],dialogues:new Map([['dlg',g]]),dialogueContextFor:()=>c};}

describe('Round155 known-choice response guide',()=>{
 it('projects the original question and current NPC without answer text',()=>{const c=context();c.knownKnowledgeNodeIds.add('choice');const rows=buildDialogueAftermathGuideEntries(input(graph(),c));expect(rows).toHaveLength(1);expect(rows[0]!.detail).toContain('核对记录');expect(rows[0]!.detail).not.toContain('不可提前泄露的答案');expect(rows[0]!.destinationId).toBe('region-guide:npc:npc');});
 it('requires a known positive knowledge gate rather than arbitrary conversation',()=>{expect(buildDialogueAftermathGuideEntries(input())).toEqual([]);const c=context();c.knownKnowledgeNodeIds.add('choice');const g=graph();g.nodes[0]!.options![0]!.conditions=[{kind:'knowledgeKnown',nodeId:'other',isKnown:false}];expect(buildDialogueAftermathGuideEntries(input(g,c))).toEqual([]);delete g.nodes[0]!.options![0]!.conditions;expect(buildDialogueAftermathGuideEntries(input(g,c))).toEqual([]);});
 it('respects additional task qualification and excludes effectful options',()=>{const c=context();c.knownKnowledgeNodeIds.add('choice');const g=graph();g.nodes[0]!.options![0]!.conditions=[...(g.nodes[0]!.options![0]!.conditions??[]),{kind:'questStatus',questId:'quest',status:'completed'}];expect(buildDialogueAftermathGuideEntries(input(g,c))).toEqual([]);done(c);expect(buildDialogueAftermathGuideEntries(input(g,c))).toHaveLength(1);g.nodes[0]!.options![0]!.effects=[{kind:'adjustRenown',delta:1}];expect(buildDialogueAftermathGuideEntries(input(g,c))).toEqual([]);});
 it('does not traverse hidden or effectful entrances',()=>{const c=context();c.knownKnowledgeNodeIds.add('choice');const g=graph();g.nodes.unshift({id:'gate',text:'入口',options:[{text:'进去',nextNodeId:'start',conditions:[{kind:'knowledgeKnown',nodeId:'gate'}]}]});g.startNodeId='gate';expect(buildDialogueAftermathGuideEntries(input(g,c))).toEqual([]);c.knownKnowledgeNodeIds.add('gate');g.nodes[0]!.options![0]!.effects=[{kind:'adjustRenown',delta:1}];expect(buildDialogueAftermathGuideEntries(input(g,c))).toEqual([]);});
 it('excludes confirmation nodes and missing NPC or dialogue',()=>{const c=context();c.knownKnowledgeNodeIds.add('choice');const g=graph();g.nodes[0]!.confirmEffects=true;expect(buildDialogueAftermathGuideEntries(input(g,c))).toEqual([]);const i=input(graph(),c);i.guide.currentMapResourceId='elsewhere';expect(buildDialogueAftermathGuideEntries(i)).toEqual([]);i.guide.currentMapResourceId='map';delete i.dialogues;expect(buildDialogueAftermathGuideEntries(i)).toEqual([]);});
 it('preserves raw indices, avoids loop duplication and uses period/follower position',()=>{const c=context();c.knownKnowledgeNodeIds.add('choice');const g=graph();g.nodes[0]!.options!.unshift({text:'再想',nextNodeId:'start'});const i=input(g,c);i.guide.periodNpcs=[{...npc,col:8,row:9}];let row=buildDialogueAftermathGuideEntries(i)[0]!;expect(row.id).toBe('aftermath:npc:start:1');expect(row.detail).toContain('(8,9)');i.guide.follower={npc,col:4,row:5,mapResourceId:'map'};row=buildDialogueAftermathGuideEntries(i)[0]!;expect(row.detail).toContain('(4,5)');expect(row.detail).toContain('P再T交谈');});
 it('leaves state unchanged and allows pure response replay',()=>{const c=context();c.knownKnowledgeNodeIds.add('choice');const i=input(graph(),c),before=JSON.stringify([[...c.knownKnowledgeNodeIds],[...c.journal.states],c.social,[...i.dialogues!]]);expect(buildDialogueAftermathGuideEntries(i)).toEqual(buildDialogueAftermathGuideEntries(i));expect(JSON.stringify([[...c.knownKnowledgeNodeIds],[...c.journal.states],c.social,[...i.dialogues!]])).toBe(before);});
 it('real cloud reserve and aid replies are mutually exclusive and no answer is leaked',()=>{const set=JSON.parse(readFileSync('data/base/dialogues/round-74-cloud-ridge-conversations.json','utf8'));const g:DialogueData=set.conversations[0],c=context();c.knownKnowledgeNodeIds.add('event.r100-well-reserve');let rows=buildDialogueAftermathGuideEntries(input(g,c));expect(rows.filter(r=>r.detail.includes('青岩驿有人带话'))).toHaveLength(1);for(const node of g.nodes.filter(node=>node.id==='r100-reserve-echo'||node.id==='r100-aid-echo'))expect(rows.map(r=>r.detail).join('')).not.toContain(node.text);const reserveId=rows.find(r=>r.detail.includes('青岩驿有人带话'))!.id;c.knownKnowledgeNodeIds.delete('event.r100-well-reserve');c.knownKnowledgeNodeIds.add('event.r100-well-aid');rows=buildDialogueAftermathGuideEntries(input(g,c));expect(rows.filter(r=>r.detail.includes('青岩驿有人带话'))).toHaveLength(1);expect(rows.find(r=>r.detail.includes('青岩驿有人带话'))!.id).not.toBe(reserveId);});
});