import {readFileSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {buildDialogueFollowupGuideEntries,type QuestGuideInput} from '../src/engine/quest-guide';
import type {DialogueData} from '../src/engine/dialogue-graph';
import type {DialogueRuntimeContext} from '../src/engine/dialogue-runtime';
import {createSocialState} from '../src/engine/social-state';
import {createFactionMembershipState} from '../src/engine/faction-system';
import type {PlacedNpc} from '../src/engine/npc-placement';
import type {WorldMapAssembly} from '../src/engine/world-map';
const context=():DialogueRuntimeContext=>({quests:new Map(),journal:{states:new Map(),trackedQuestId:null},items:new Map(),inventory:null,social:createSocialState(),speakerNpcId:'npc',knownKnowledgeNodeIds:new Set(),knowledgeNodes:new Map(),character:null,factions:new Map(),martialArts:new Map(),factionState:createFactionMembershipState(),timeOfDayPeriodId:'morning'});
function done(c:DialogueRuntimeContext,id='quest'){c.journal.states.set(id,{questId:id,status:'completed',objectiveCounts:new Map()});}
const graph=():DialogueData=>({id:'dlg',startNodeId:'start',nodes:[{id:'start',text:'入口',options:[{text:'核对记录',nextNodeId:'answer',conditions:[{kind:'questStatus',questId:'quest',status:'completed'}],effects:[{kind:'discoverKnowledgeNode',nodeId:'new'}]}]},{id:'answer',text:'不可提前泄露的答案'}]});
const npc:PlacedNpc={record:{id:'npc',name:'测试人',mapResourceId:'map',position:{col:1,row:2},dialogueId:'dlg',shopId:null,questGiver:false,schedule:[]},col:1,row:2};
function input(g=graph(),c=context()):QuestGuideInput{return {guide:{worldMap:{} as WorldMapAssembly,currentMapResourceId:'map',baseNpcs:[npc],shops:new Map(),items:new Map(),shopStocks:new Map(),knownKnowledgeNodeIds:c.knownKnowledgeNodeIds},quests:new Map(),journal:c.journal,access:{},encounters:[],dialogues:new Map([['dlg',g]]),dialogueContextFor:()=>c};}
function ready(){const c=context();done(c);return input(graph(),c);}
describe('Round154 task completion follow-up projections',()=>{
 it('points to original question and NPC without revealing answer or claiming completion',()=>{const row=buildDialogueFollowupGuideEntries(ready())[0]!;expect(row.detail).toContain('核对记录');expect(row.detail).not.toContain('不可提前泄露的答案');expect(row.detail).toContain('本页不展示答案');expect(row.destinationId).toBe('region-guide:npc:npc');});
 it('honours unfinished tasks and disappears after discovery',()=>{const c=context();expect(buildDialogueFollowupGuideEntries(input(graph(),c))).toEqual([]);done(c);c.knownKnowledgeNodeIds.add('new');expect(buildDialogueFollowupGuideEntries(input(graph(),c))).toEqual([]);});
 it('excludes arbitrary discoveries lacking a completed-task gate',()=>{const g=graph();delete g.nodes[0]!.options![0]!.conditions;expect(buildDialogueFollowupGuideEntries(input(g,context()))).toEqual([]);});
 it('excludes mixed spending/reward effects and confirmation decisions',()=>{const g=graph(),c=context();done(c);g.nodes[0]!.options![0]!.effects=[...(g.nodes[0]!.options![0]!.effects??[]),{kind:'adjustRenown',delta:1}];expect(buildDialogueFollowupGuideEntries(input(g,c))).toEqual([]);g.nodes[0]!.options![0]!.effects=[{kind:'discoverKnowledgeNode',nodeId:'new'}];g.nodes[0]!.confirmEffects=true;expect(buildDialogueFollowupGuideEntries(input(g,c))).toEqual([]);});
 it('does not traverse a hidden or effectful entrance',()=>{const g=graph(),c=context();done(c);g.nodes.unshift({id:'gate',text:'入口',options:[{text:'走入',nextNodeId:'start',conditions:[{kind:'knowledgeKnown',nodeId:'gate'}]}]});g.startNodeId='gate';expect(buildDialogueFollowupGuideEntries(input(g,c))).toEqual([]);c.knownKnowledgeNodeIds.add('gate');g.nodes[0]!.options![0]!.effects=[{kind:'adjustRenown',delta:1}];expect(buildDialogueFollowupGuideEntries(input(g,c))).toEqual([]);});
 it('handles loops without duplicate candidates and preserves raw option indices',()=>{const g=graph(),c=context();done(c);g.nodes[0]!.options!.unshift({text:'再想',nextNodeId:'start'});const rows=buildDialogueFollowupGuideEntries(input(g,c));expect(rows).toHaveLength(1);expect(rows[0]!.id).toBe('followup:npc:start:1');});
 it('requires actual current NPC and dialogue data, preserving old callers',()=>{const i=ready();delete i.dialogues;expect(buildDialogueFollowupGuideEntries(i)).toEqual([]);i.dialogues=new Map([['dlg',graph()]]);i.guide.currentMapResourceId='other';expect(buildDialogueFollowupGuideEntries(i)).toEqual([]);i.guide.currentMapResourceId='map';i.guide.baseNpcs=[];expect(buildDialogueFollowupGuideEntries(i)).toEqual([]);});
 it('reads actual period and follower placement and talk key',()=>{const i=ready();i.guide.periodNpcs=[{...npc,col:8,row:9}];expect(buildDialogueFollowupGuideEntries(i)[0]!.detail).toContain('(8,9)');i.guide.follower={npc,col:4,row:5,mapResourceId:'map'};expect(buildDialogueFollowupGuideEntries(i)[0]!.detail).toContain('P再T交谈');expect(buildDialogueFollowupGuideEntries(i)[0]!.detail).toContain('(4,5)');});
 it('projection never discovers, rewards or changes the journal',()=>{const i=ready(),c=i.dialogueContextFor!('npc');const before=JSON.stringify([[...c.knownKnowledgeNodeIds],[...c.journal.states],c.social,[...i.dialogues!]]);buildDialogueFollowupGuideEntries(i);expect(JSON.stringify([[...c.knownKnowledgeNodeIds],[...c.journal.states],c.social,[...i.dialogues!]])).toBe(before);});
 it('real mainland crosscheck and close require their own gates and disappear independently',()=>{const set=JSON.parse(readFileSync('data/base/dialogues/round-74-cloud-ridge-conversations.json','utf8'));const g:DialogueData=set.conversations[0];const c=context();for(const id of ['quest.r62-post-ledger','quest.r67-well-waterline','quest.r74-cloud-marks'])done(c,id);let rows=buildDialogueFollowupGuideEntries(input(g,c));expect(rows.some(r=>r.detail.includes('把更簿、井壁和石阶对照'))).toBe(true);expect(rows.some(r=>r.detail.includes('三地调查与清道完成'))).toBe(false);expect(rows.map(r=>r.detail).join('')).not.toContain('旁边留着新拓纸纤维');c.knownKnowledgeNodeIds.add('event.r100-paper-crosscheck');for(const id of ['quest.r62-clear-ridge-road','quest.r74-cloud-bridge'])done(c,id);c.knownKnowledgeNodeIds.add('event.r100-record-settled');c.knownKnowledgeNodeIds.add('event.r100-well-settled');rows=buildDialogueFollowupGuideEntries(input(g,c));expect(rows.some(r=>r.detail.includes('把更簿、井壁和石阶对照'))).toBe(false);expect(rows.some(r=>r.detail.includes('三地调查与清道完成'))).toBe(true);c.knownKnowledgeNodeIds.add('event.r100-mainland-close');rows=buildDialogueFollowupGuideEntries(input(g,c));expect(rows.some(r=>r.detail.includes('三地调查与清道完成'))).toBe(false);expect(rows.some(r=>r.detail.includes('把更簿、井壁和石阶对照'))).toBe(false);expect(rows.some(r=>r.detail.includes('转述给另一处的记录人'))).toBe(true);});
});
