import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, cpSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, resolve, sep } from 'node:path';
import { parseBattleEncounterSet, CombatSession } from '../src/engine/turn-based-combat';
import { parseCharacterProfileSet, parseMartialArtSet, createCharacterState, grantExperience } from '../src/engine/character-progression';
import { parseDialogueSet } from '../src/engine/dialogue-graph';
import { parseQuestSet, createQuestJournal, acceptQuest, applyQuestSignal } from '../src/engine/quest-system';
import { encounterId, behavior, dialoguePatches, repairEncounterRaw, repairDialogueRaw } from '../scripts/lib/round276-cloud-challenge.mjs';
const root=resolve('.'),battlePath='data/base/battles/round-05-encounters.json',dialoguePath='data/base/dialogues/round-74-cloud-ridge-conversations.json';
const raw=(p:string)=>readFileSync(join(root,p),'utf8'),json=(p:string)=>JSON.parse(raw(p));
const baseline=(p:string)=>execFileSync('git',['show','2a5941e:'+p],{encoding:'utf8',maxBuffer:32*1024*1024});
const encounters=parseBattleEncounterSet(json(battlePath)),profiles=parseCharacterProfileSet(json('data/base/characters/round-04-profiles.json')),skills=parseMartialArtSet(json('data/base/skills/round-04-martial-arts.json'));
if(!encounters.ok||!profiles.ok||!skills.ok)throw Error('shipped battle data refused');
const record=encounters.set.encounters.find(e=>e.id===encounterId)!,profile=profiles.set.profiles[0]!,arts=new Map(skills.set.martialArts.map(a=>[a.id,a]));
function battle(branch:'escort'|'repair'='escort',zero=false){const saved=json('iterations/round-275/c0-'+branch+'-arrival.json').snapshot;const player=createCharacterState(profile);grantExperience(profile,player,saved.player.experience);player.health.current=saved.player.healthCurrent;player.qi.current=saved.player.qiCurrent;player.martialArtIds=[...saved.player.martialArtIds];grantExperience(profile,player,28);const encounter=structuredClone(record);if(zero)encounter.enemy.qi=0;return {player,session:new CombatSession({encounter,profile,player,martialArts:arts})};}
describe('Round276 cloud challenge is readable and remains a real threat',()=>{
  it('actual C0 plus completed marks upgrades before battle and preserves remaining wounds/qi',()=>{const escort=battle(),repair=battle('repair');expect(escort.player.level).toBe(8);expect(repair.player.level).toBe(8);expect(escort.player.health.current).toBe(208);expect(repair.player.health.current).toBe(206);expect(escort.player.qi.current).toBe(121);expect(escort.player.experience).toBe(714);expect(repair.player.experience).toBe(702);});
  it('actual guarded four-turn and unguarded three-turn plans spend different health/qi budgets',()=>{const guard=battle(),attack=battle(),start=guard.player.health.current,qi=guard.player.qi.current;for(const action of ['skill.jianghu-sanshou','skill.r32-yunyin-buyun-lu','skill.jianghu-sanshou','skill.jianghu-sanshou'])guard.session.playerUse(action);for(let i=0;i<3;i++)attack.session.playerUse('skill.jianghu-sanshou');expect(guard.session.finalResult?.outcome).toBe('victory');expect(attack.session.finalResult?.outcome).toBe('victory');expect(start-guard.player.health.current).toBe(23);expect(start-attack.player.health.current).toBe(42);expect(guard.player.qi.current).toBe(qi-3);expect(attack.player.qi.current).toBe(qi);});
  it('preserves all historical numbers, identity, repeatability, rewards and other encounters',()=>{const old=JSON.parse(baseline(battlePath)),current=json(battlePath);const e=current.encounters.find((e:{id:string})=>e.id===encounterId);expect(e.enemy.behavior).toEqual(behavior);delete e.enemy.behavior;expect(current).toEqual(old);expect(record.repeatable).toBe(true);expect(record.victoryExperience).toBe(48);});
  it('normal strike → heavy preparation → recovery cues match actual turns',()=>{const {player,session}=battle(),start=player.health.current;expect(session.enemyIntent).toContain('短打');session.playerWait();expect(player.health.current).toBeLessThan(start);expect(session.enemyIntent).toContain('守御可卸蓄势');const before=player.health.current,preview=Number(session.enemyIntent!.match(/预计未守御伤害 (\d+)/)![1]);session.playerWait();expect(before-player.health.current).toBe(preview);expect(session.enemyIntent).toContain('本回合不攻击');const recovering=player.health.current;session.playerWait();expect(player.health.current).toBe(recovering);expect(session.enemyView.qi.current).toBe(16);expect(session.enemyIntent).toContain('短打');});
  it('guard costs qi and a turn, reduces damage and specifically unloads the heavy bonus',()=>{const plain=battle(),guard=battle();plain.session.playerWait();guard.session.playerWait();const before=guard.player.health.current,qi=guard.player.qi.current;plain.session.playerWait();guard.session.playerUse('skill.r32-yunyin-buyun-lu');expect(guard.player.health.current).toBeGreaterThan(plain.player.health.current);expect(guard.player.health.current).toBeLessThan(before);expect(guard.player.qi.current).toBe(qi-3);expect(guard.session.log.at(-1)?.text).toContain('蓄势已卸去');});
  it('zero enemy qi falls back to available attacks; recovery is not a hidden strike',()=>{const {player,session}=battle('escort',true);const start=player.health.current;session.playerWait();expect(player.health.current).toBeLessThan(start);const second=player.health.current;expect(session.enemyIntent).toContain('改用可用招式');session.playerWait();expect(player.health.current).toBeLessThan(second);const third=player.health.current;session.playerWait();expect(player.health.current).toBe(third);expect(session.enemyView.qi.current).toBe(0);});
  for(const branch of ['escort','repair'] as const)it(branch+' C0 can win using learned preparation; battle reward only once per session',()=>{const {player,session}=battle(branch),start=player.health.current,xp=player.experience;for(const action of ['skill.jianghu-sanshou','skill.r32-yunyin-buyun-lu','skill.jianghu-sanshou','skill.jianghu-sanshou'])session.playerUse(action);expect(session.finalResult?.outcome).toBe('victory');expect(player.health.current).toBeLessThan(start);expect(player.experience).toBe(xp+48);session.playerWait();expect(player.experience).toBe(xp+48);});
});
describe('Round276 local investigation and authors remain bounded',()=>{
  it('local chain requires real discovery before acceptance of challenge, quest reward settles once',()=>{const parsed=parseQuestSet(json('data/base/quests/round-74-cloud-ridge-quests.json'));if(!parsed.ok)throw Error(parsed.errors.join());const quests=new Map(parsed.set.quests.map(q=>[q.id,q])),journal=createQuestJournal(quests),marks='quest.r74-cloud-marks',bridge='quest.r74-cloud-bridge';expect(acceptQuest(quests,journal,bridge).ok).toBe(false);expect(acceptQuest(quests,journal,marks).ok).toBe(true);expect(applyQuestSignal(quests,journal,{type:'encounter-victory',encounterId}).completed).toEqual([]);expect(applyQuestSignal(quests,journal,{type:'knowledge-discovery',nodeId:'place.r74-cloud-markers'}).completed.map(c=>c.questId)).toEqual([marks]);expect(quests.get(marks)!.rewards).toEqual({experience:28,currency:20});expect(acceptQuest(quests,journal,bridge).ok).toBe(true);expect(applyQuestSignal(quests,journal,{type:'encounter-victory',encounterId}).completed.map(c=>c.questId)).toEqual([bridge]);expect(quests.get(bridge)!.rewards).toEqual({experience:44,currency:32});expect(applyQuestSignal(quests,journal,{type:'encounter-victory',encounterId}).completed).toEqual([]);});
  it('changes only three local texts, preserving every condition/effect and prior arrival/shop layer',()=>{const old=JSON.parse(baseline(dialoguePath)),current=json(dialoguePath);for(const p of dialoguePatches){const n=current.conversations[0].nodes.find((n:{id:string})=>n.id===p.id);expect(n.text).toBe(p.after);expect(n.options).toBeUndefined();n.text=p.before;}expect(current).toEqual(old);expect(parseDialogueSet(json(dialoguePath)).ok).toBe(true);expect(dialoguePatches.find(p=>p.id==='bridge-complete')!.after).toContain('护索尚待修补');});
  for(const [path,repair] of [[battlePath,repairEncounterRaw],[dialoguePath,repairDialogueRaw]] as const)it(path+' replays exact current records and keeps LF/CRLF byte idempotence',()=>{expect(repair(baseline(path)).replace(/\r\n/g,'\n')).toBe(raw(path).replace(/\r\n/g,'\n'));for(const eol of ['\n','\r\n']){const input=raw(path).replace(/\r?\n/g,eol);expect(repair(input)).toBe(input);}});
  it('drifted loop/base values and duplicate encounters refuse',()=>{const d=json(battlePath),e=d.encounters.find((e:{id:string})=>e.id===encounterId);e.enemy.behavior[1].powerBonus=99;expect(()=>repairEncounterRaw(JSON.stringify(d))).toThrow('漂移');delete e.enemy.behavior;e.enemy.health=65;expect(()=>repairEncounterRaw(JSON.stringify(d))).toThrow('基值');e.enemy.health=64;d.encounters.push(structuredClone(e));expect(()=>repairEncounterRaw(JSON.stringify(d))).toThrow('不唯一');});
  it('drifted and duplicate local nodes refuse',()=>{const d=json(dialoguePath),n=d.conversations[0].nodes.find((n:{id:string})=>n.id===dialoguePatches[0]!.id);n.text='漂移';expect(()=>repairDialogueRaw(JSON.stringify(d))).toThrow('漂移');n.text=dialoguePatches[0]!.after;d.conversations[0].nodes.push({...n});expect(()=>repairDialogueRaw(JSON.stringify(d))).toThrow('不唯一');});
  it('CLI preflights both resources before any write, is cwd independent and idempotent',()=>{const temp=mkdtempSync(join(tmpdir(),'wuxia-r276-'));try{for(const dir of ['scripts/lib','data/base/battles','data/base/dialogues'])mkdirSync(join(temp,dir),{recursive:true});for(const p of ['scripts/apply-round276.mjs','scripts/lib/round276-cloud-challenge.mjs'])cpSync(join(root,p),join(temp,p));writeFileSync(join(temp,battlePath),baseline(battlePath));writeFileSync(join(temp,dialoguePath),'{}');const before=readFileSync(join(temp,battlePath));const run=()=>execFileSync(process.execPath,[join(temp,'scripts/apply-round276.mjs')],{cwd:tmpdir(),stdio:'pipe'});expect(run).toThrow();expect(readFileSync(join(temp,battlePath))).toEqual(before);writeFileSync(join(temp,dialoguePath),baseline(dialoguePath));run();const after=readFileSync(join(temp,battlePath));run();expect(readFileSync(join(temp,battlePath))).toEqual(after);expect(JSON.parse(after.toString())).toEqual(json(battlePath));}finally{if(!resolve(temp).startsWith(resolve(tmpdir())+sep+'wuxia-r276-'))throw Error('unsafe sandbox');rmSync(temp,{recursive:true,force:true});}},20000);
});
