import {readFileSync} from 'node:fs';
import {describe,it,expect,vi} from 'vitest';
vi.mock('phaser',()=>({default:{Scene:class{},Input:{Keyboard:{KeyCodes:{}}},Scenes:{Events:{SHUTDOWN:'shutdown'}},Math:{Vector2:class{constructor(public x=0,public y=0){}}}}}));
import {GridScene} from '../src/game/grid-scene';
import {parseAchievementSet,createAchievementRunState} from '../src/engine/achievement-system';
import {parseCharacterProfileSet,createCharacterState,cumulativeExperienceForLevel} from '../src/engine/character-progression';
import {parseItemSet,indexItems,createInventoryState,countItem} from '../src/engine/item-system';
import {parseQuestSet,createQuestJournal} from '../src/engine/quest-system';
import {parseDialogueSet,DialogueSession} from '../src/engine/dialogue-graph';
import {createSocialState} from '../src/engine/social-state';
import {createFactionMembershipState} from '../src/engine/faction-system';
import type {DialogueRuntimeContext} from '../src/engine/dialogue-runtime';
const read=(p:string)=>JSON.parse(readFileSync('data/base/'+p,'utf8'));
function host(){const a=parseAchievementSet(read('achievements/round-28-achievements.json')),p=parseCharacterProfileSet(read('characters/round-04-profiles.json')),i=parseItemSet(read('items/round-06-items.json')),q=parseQuestSet(read('quests/round-07-quests.json')),d=parseDialogueSet(read('dialogues/round-03-conversations.json'));if(!a.ok||!p.ok||!i.ok||!q.ok||!d.ok)throw Error('fixture');const profile=p.set.profiles[0]!,character=createCharacterState(profile),inventory=createInventoryState(profile,[{itemId:'item.huichun-gao',quantity:16}]),social=createSocialState(),quests=new Map(q.set.quests.map(q=>[q.id,q])),journal=createQuestJournal(quests);journal.states.get('quest.round-07-medicine-run')!.status='completed';journal.states.get('quest.round-07-clear-alley')!.status='completed';social.morality=-15;character.level=12;character.experience=cumulativeExperienceForLevel(profile,12);inventory.currency=268;const factionState=createFactionMembershipState();const ctx:DialogueRuntimeContext={quests,journal,inventory,social,items:indexItems(i.set).byId,speakerNpcId:'char.ma-shangyi',knownKnowledgeNodeIds:new Set(),knowledgeNodes:new Map(),character,factions:new Map(),martialArts:new Map(),factionState,timeOfDayPeriodId:'period.morning'};const state=createAchievementRunState();state.unlockedIds=a.set.achievements.filter(x=>!['achievement.kind-deed','achievement.name-in-the-rivers'].includes(x.id)).map(x=>x.id);const scene=new GridScene();Object.assign(scene,{world:{assembly:{achievements:a.set}},playerProfile:profile,playerState:character,inventory,social,questJournal:journal,factionState,achievementState:state,knownKnowledgeNodeIds:ctx.knownKnowledgeNodeIds,showRegionNotice:vi.fn(),syncKnowledgeFromRunFacts:vi.fn(),dialogueContextFor:()=>ctx});const internals=scene as unknown as{confirmDialogueOption:(id:string,s:DialogueSession,index:number)=>{advanced:boolean;feedback:string|null};refreshAchievementUnlocks:()=>string[]};const conversation=d.set.conversations.find(c=>c.id==='dlg.ma-shangyi-notice-board')!;const donate=()=>{const session=new DialogueSession({...conversation,startNodeId:'board'});return internals.confirmDialogueOption(ctx.speakerNpcId,session,0);};return{scene,internals,profile,character,inventory,social,ctx,donate};}
describe('Round128 real scene dialogue achievement receipts',()=>{
 it('five costed donations pay exactly two first achievements, separate from quest rewards, then no repeat',()=>{const h=host(),lines=[];for(let n=0;n<5;n++){const r=h.donate();expect(r.advanced).toBe(true);lines.push(r.feedback!);}expect(h.inventory.currency).toBe(338);expect(countItem(h.inventory,'item.huichun-gao')).toBe(1);expect(h.social.morality).toBe(10);expect(h.social.renown).toBe(25);expect(lines[0]).not.toContain('首次成就');expect(lines[1]).toContain('首次成就「小有名声」：经验 +45 · 银两 +40');expect(lines[3]).toContain('首次成就「善念初明」：经验 +35 · 银两 +30');expect(lines[4]).not.toContain('首次成就');expect(h.internals.refreshAchievementUnlocks()).toEqual([]);expect(h.inventory.currency).toBe(338);expect(h.donate()).toEqual({advanced:false,feedback:null});});
 it('receipts show actual capped currency and discarded max-level experience, still unlock once',()=>{const h=host();h.social.morality=5;h.social.renown=10;h.inventory.currency=999_999_998;h.character.level=h.profile.maxLevel;h.character.experience=cumulativeExperienceForLevel(h.profile,h.profile.maxLevel);const receipt=h.internals.refreshAchievementUnlocks();expect(receipt).toHaveLength(2);expect(receipt[0]).toContain('经验 +0 · 银两 +1');expect(receipt[1]).toContain('经验 +0 · 银两 +0');expect(h.inventory.currency).toBe(999_999_999);expect(h.internals.refreshAchievementUnlocks()).toEqual([]);});
 it('without playable profile returns no receipt or mutation',()=>{const h=host();Object.assign(h.scene,{playerProfile:null});expect(h.internals.refreshAchievementUnlocks()).toEqual([]);expect(h.inventory.currency).toBe(268);});
});
