import {readFileSync} from 'node:fs';
import {describe,it,expect,vi} from 'vitest';
import type Phaser from 'phaser';
vi.mock('phaser',()=>({default:{Input:{Keyboard:{KeyCodes:{UP:1,W:2,DOWN:3,S:4,ENTER:5,ESC:6,PAGE_UP:7,PAGE_DOWN:8}}}}}));
vi.mock('../src/game/ui-theme',()=>({UI_FONT_FAMILY:'monospace',addPixelPanelChrome:()=>{},addPixelSelection:()=>{}}));
vi.mock('../src/game/settings',()=>({uiFontSize:(n:number)=>`${n}px`}));
import {BattlePanel} from '../src/game/combat-ui';
import {CombatSession,parseBattleEncounterSet} from '../src/engine/turn-based-combat';
import {createCharacterState,parseCharacterProfileSet,parseMartialArtSet} from '../src/engine/character-progression';
const read=(p:string)=>JSON.parse(readFileSync(new URL('../'+p,import.meta.url),'utf8'));
function setup(legacy=false){const pp=parseCharacterProfileSet(read('data/base/characters/round-04-profiles.json')),ap=parseMartialArtSet(read('data/base/skills/round-04-martial-arts.json')),bp=parseBattleEncounterSet(read('data/base/battles/round-05-encounters.json'));if(!pp.ok||!ap.ok||!bp.ok)throw Error('base');const profile=pp.set.profiles[0]!,player=createCharacterState(profile),encounter=structuredClone(bp.set.encounters[0]!);if(legacy)delete encounter.enemy.behavior;const session=new CombatSession({encounter,profile,player,martialArts:new Map(ap.set.martialArts.map(a=>[a.id,a]))});const keys=new Map<number,Set<()=>void>>(),shown:{text:string;destroyed:boolean}[]=[],container={setVisible(){return this},setDepth(){return this},add(){return this},removeAll(){for(const t of shown)t.destroyed=true;return this},destroy(){}};const scene={scale:{width:960,height:540},input:{keyboard:{addKey(code:number){if(!keys.has(code))keys.set(code,new Set());return {on(_e:string,fn:()=>void){keys.get(code)!.add(fn)},off(_e:string,fn:()=>void){keys.get(code)!.delete(fn)}};}}},add:{container:()=>container,rectangle:()=>({setStrokeStyle(){return this}}),text:(_x:number,_y:number,text:string)=>{const t={text,destroyed:false,height:21,width:0,setText(value:string){this.text=value;this.width=value.length*13;return this},setLineSpacing(){return this},setOrigin(){return this},setPosition(){return this},destroy(){this.destroyed=true}};shown.push(t);return t;}}} as unknown as Phaser.Scene;let closed=0;const panel=new BattlePanel(scene,{onClose:()=>closed++});panel.open(session);return {panel,session,player,visible:()=>shown.filter(t=>!t.destroyed).map(t=>t.text),closed:()=>closed,press:(code:number)=>{for(const fn of [...keys.get(code)??[]])fn();}};}
describe('Round107 actual battle panel callbacks',()=>{
 it('visible intention updates immediately with every accepted keyboard action',()=>{const r=setup();expect(r.visible()).toContain(`敌方下一步：${r.session.enemyIntent}`);const before=r.session.enemyIntent;r.press(5);expect(r.session.enemyIntent).not.toBe(before);expect(r.visible()).toContain(`敌方下一步：${r.session.enemyIntent}`);expect(r.visible().some(t=>t.includes('守御可卸蓄势'))).toBe(true);});
 it('refused unaffordable action preserves visible intention and resources',()=>{const r=setup();r.player.qi.current=0;r.press(3);const before=r.session.enemyIntent,hp=r.player.health.current;r.press(5);expect(r.session.enemyIntent).toBe(before);expect(r.player.health.current).toBe(hp);expect(r.visible()).toContain(`敌方下一步：${before}`);});
 it('Escape ends combat and removes the intention, then closes and unbinds',()=>{const r=setup();r.press(6);expect(r.session.finalResult?.outcome).toBe('fled');expect(r.visible().some(t=>t.startsWith('敌方下一步'))).toBe(false);r.press(6);expect(r.closed()).toBe(1);r.press(5);expect(r.closed()).toBe(1);});
 it('legacy enemies still show their log and no invented strategy preview',()=>{const r=setup(true);expect(r.visible().some(t=>t.startsWith('敌方下一步'))).toBe(false);r.press(5);expect(r.visible().some(t=>t.includes('造成'))).toBe(true);r.panel.destroy();});
});
